### ISSUE TITLE
fuse_nfs hangs when used in multithread mode

### ISSUE THREAD

**Issue by varung** [sahlberg/libnfs#102]
I compiled and mounted a fuse file system using fuse_nfs in the examples folder. I have a file that I created by doing "seq" that is 932M long. If I use libnfs directly to read this file, I'm successful. For instance, nfs_cp works fine. However, when I try to read this file using fuse_nfs, it hangs after reading some number of lines. I noticed that fuse by default uses multiple threads, and I thought that maybe this was causing the problem. It hangs after reading about "699319" lines from the file. I inserted logging statements, and found that nfs_pread waits indefinitely for nfs.

nfs_pread async count=131072 offset=2949120 => never returns

I don't understand why pread is hanging when used from fuse, but works when I run it directly. 

Update:
I updated fuse_nfs to pass different arguments to fuse: "-s" which forces single thread. This seems to "solve" the problem. I guess fuse_nfs is not intended to run multithreaded. Would it be advisable to modify fuse_nfs to support multithreaded use by creating a unique nfs context for each thread?

**Comment by sahlberg** [comment]
Can you get me a network trace for this?  Else I can try to reproduce in a
few days or so.

**Comment by sahlberg** [comment]
I believe this is fixed in :

commit a5042b9857617ea91e84f7f1949d696470183b64
Author: Alexander Graf <agraf@suse.de>
Date:   Sun Feb 15 01:49:22 2015 +0100

Thanks Alexander!

**Comment by varung** [comment]
Hi
Ah I was hoping for a multithreaded implementation, not disabling mt.

To make fuse work with mt, would you recommend having a thread local
version of libnfs context, or wrap a mutex around the global one? Are the
functions themselves thread safe(ie no static variables)?

Thanks

**Comment by sahlberg** [comment]
Libnfs is not threads safe, and I don't know if I want to make it threads safe with alll the locking that contains.

A thread local nfs_context for each thread should work. There are no, or should not be, any global variables.
