### ISSUE TITLE
truncate failure: length type demotion and sign extension on promotion

### ISSUE THREAD

**Issue by doktorstick** [sahlberg/libnfs#106]
`nfs_truncate` fails due to type demotion and sign-extension. For example, truncating to size `0x280000000` is `0xffffffff80000000` on the wire due to the `uint64_t` -> `int` -> `uint64_t` path in `nfs_truncate_async` (i.e., `0x280000000` -> `0x80000000` -> `0xffffffff80000000`)

In `nfs_truncate_async`, the 64-bit value is passed into the last parameter of `nfs_lookuppath_async`, which is `int continue_int`. This is stored in `nfs_cb_data->continue_int`, which is also an `int`.  In `nfs_truncate_continue_internal` it converted back into a 64-bit `uint64_t offset = data->continue_int;`

I'm on 1.9.4, but looking at the code on github, the problem is still there.

`Linux jayne01 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by sahlberg** [comment]
Thanks. I changed continue_int to be a uint64_t instead which should fix it.

Thanks!
