### ISSUE TITLE
Question: Does libnfs support NFS v4 and NFS v4.1?

### ISSUE THREAD

**Issue by allspace** [sahlberg/libnfs#110]
This is just a question:

Does libnfs support NFS v4 and NFS v4.1? If not, any plan?

**Comment by sahlberg** [comment]
On Sat, Feb 21, 2015 at 6:22 PM, allspace <notifications@github.com> wrote:

> This is just a question:
>
> Does libnfs support NFS v4 and NFS v4.1? If not, any plan?
>

No. No v4 support today.


I have thought some about adding basic v4 support but it is not high on my
use case list.
I wouldn't mind adding v4 support but it is not anything planned near term.

**Comment by allspace** [comment]
ok, thank you!
