### ISSUE TITLE
build: rpc_get_error return casting

### ISSUE THREAD

**Issue by doktorstick** [sahlberg/libnfs#111]
Howdy. I encountered a problem with a crash in `rpc_set_error`, inside `vsnprintf`--specifically, the `char*` variable argument to a `"%s"` format specifier. I tracked it down to an implicit casting problem with `rpc_get_error` that wasn't warned about during `make clean && make`. This is on 1.9.4, and I'm adding this mainly for posterity because the include order in 1.9.7 fixes it for 1.9.4, and if there's a general build problem that can mask errors, it may want to be investigated.

For reference:
```c
char *rpc_get_error(struct rpc_context *rpc)
{
        assert(rpc->magic == RPC_CONTEXT_MAGIC);
        return rpc->error_string;
}
```
Here's we are, inside of `rpc_get_error()` about to return.
```
(gdb) p rpc->error_string
$10 = 0x7feef08547e0 "libnfs_rpc_reply_body failed to decode ACCEPTED"
(gdb) list
  0x00007fef00f4f120 <+56>:    mov    -0x8(%rbp),%rax
  0x00007fef00f4f124 <+60>:    mov    0x10(%rax),%rax
=> 0x00007fef00f4f128 <+64>:    leaveq
  0x00007fef00f4f129 <+65>:    retq
gdb) p/x $rax
$12 = 0x7feef08547e0
```
That looks correct, but when I finish  function:
```
(gdb) p/x $rax
$13 = 0xfffffffff08547e0
```
The code in question was in `libnfs_rpc_msg`:
```c
        case REPLY:
                ret = libnfs_rpc_reply_body(rpc, zdrs, &msg->body.rbody);
                if (!ret) {
                  rpc_set_error(rpc, "libnfs_rpc_msg failed to decode "
                                "REPLY, ret=%d: %s", ret, rpc_get_error(rpc));
                }
                return ret;
```
and I changed it the following:
```c
        case REPLY:
                ret = libnfs_rpc_reply_body(rpc, zdrs, &msg->body.rbody);
                if (!ret) {
                  char *current = (char*) rpc_get_error (rpc);
                  rpc_set_error(rpc, "libnfs_rpc_msg failed to decode "
                                "REPLY, ret=%d: %s", ret, current);
                }
                return ret;
```

During compile this popped up, confirming the implicit cast:
```c
libnfs-zdr.c: In function 'libnfs_rpc_msg':
libnfs-zdr.c:467:35: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
        char *current = (char*) rpc_get_error (rpc);
```

When I added the prototype `char *rpc_get_error(struct rpc_context *rpc);` to `libnfs_zdr.c`, the warning went away and `$rax` remained 64-bits; no more crashing.

I tracked down the original prototype of `rpc_get_error`--it's in `libnfs-raw.h`, and it's correct, but the include chain isn't correct:  `libnfs-zdr.c` includes `libnfs-zdr.h`--`libnfs-raw.h` isn't pulled in at all.

Now, in the `master` version, `libnfs-zdr.c` eventually includes `libnfs-raw.h`, so it may be moot, though disturbing. I was able to mimic the includes and get it working without my prototype hack.

**Comment by sahlberg** [comment]
-Wall -Werror should have caught that straight away.

I have added and pushed support to use some good -W flags when building
so that we will catch that if it reoccurs.

Thanks for your detailed bugreport!
