### ISSUE TITLE
nfs-cp doesn't compile on osx

### ISSUE THREAD

**Issue by Memphiz** [sahlberg/libnfs#136]
follwing error:

`/usr/bin/clang -DHAVE_CONFIG_H -I. -I..  -I/Users/memphis/src/xbmc-memphiz/tools/depends/target/libnfs/macosx10.10_x86_64-target/include -I/Users/memphis/src/xbmc-memphiz/tools/depends/target/libnfs/macosx10.10_x86_64-target/include/nfsc -I/Users/memphis/src/xbmc-memphiz/tools/depends/target/libnfs/macosx10.10_x86_64-target/mount "-D_U_=__attribute__((unused))" -fheinous-gnu-extensions -no-cpp-precomp -arch x86_64 -mmacosx-version-min=10.7  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -isystem /Users/Shared/xbmc-depends/macosx10.10_x86_64-target/include   -fheinous-gnu-extensions -no-cpp-precomp -arch x86_64 -mmacosx-version-min=10.7  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -isystem /Users/Shared/xbmc-depends/macosx10.10_x86_64-target/include -DHAVE_NET_IF_H -D_FILE_OFFSET_BITS=64 -MT nfs-cp.o -MD -MP -MF .deps/nfs-cp.Tpo -c -o nfs-cp.o nfs-cp.c
nfs-cp.c:107:7: error: no member named 'st_atim' in 'struct stat'
                st->st_atim.tv_sec  = nfs_st.nfs_atime;
                ~~  ^
nfs-cp.c:108:7: error: no member named 'st_mtim' in 'struct stat'
                st->st_mtim.tv_sec  = nfs_st.nfs_mtime;
                ~~  ^
nfs-cp.c:109:7: error: no member named 'st_ctim' in 'struct stat'
                st->st_ctim.tv_sec  = nfs_st.nfs_ctime;
                ~~  ^
3 errors generated.
make[3]: *** [nfs-cp.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [macosx10.10_x86_64-target/lib/.libs/libnfs.a] Error 2`

**Comment by sahlberg** [comment]
That should work now as we no longer use  st_atim.tv_sec  but st_atime in nfs-cp.c
