### ISSUE TITLE
XFS file-system with inode64 option causes directories to be unreadable

### ISSUE THREAD

**Issue by cjthompson** [sahlberg/libnfs#142]
I have an XFS filesystem with the `inode64` option enabled (which is default in Ubuntu 14.04+).  I noticed  while using Kodi, which uses libnfs, that browsing my NFS shares, any directory that had an inode value greater than the 32-bit max value came back with no attributes and thus Kodi didn't see it as a browsable directory.  This issue does not seem to be an issue when accessing files has have large inode values.

For a lengthier discussion and more details about the issue, see http://forum.kodi.tv/showthread.php?tid=258184&pid=2270300

I'm not entirely certain whether or not this is a client or server issue, but I do know that Kodi on Android and Linux couldn't browse directories but OS X native NFS client was able to browse the same directories.

**Comment by sahlberg** [comment]
I think it might be a case of libnfs not having a workaround for servers that return neither a handle nor attributes for a directory entry.

This is interesting :
file id: 2429 name: Music name attributes:  type: DIR mode: OWNER_READ OWNER_WRITE OWNER_EXEC GROUP_READ GROUP_WRITE GROUP_EXEC OTHER_READ OTHER_EXEC nlink: 8 uid: 1000 gid: 1000 size: 96 used: 4096 rdev:  specdata1: 0 specdata2: 0 fsid: 0 fileid: 2429 atime: seconds: 1454459047 nseconds: 426231589  mtime: seconds: 1419893363 nseconds: 159754539  ctime: seconds: 1419893363 nseconds: 159754539  name handle:  handle: Commit:0100018 cookie: 30
file id: 56908316928 name: Old TV Shows name attributes:  void  name handle:  void  cookie: 36
file id: 25772617057 name: Pictures name attributes:  void  name handle:  void  cookie: 39

Once I know how this server is unusual I should be able to implement a workaround.

Can you collect a wireshark trace of
1, osx accessing the same directory so I can see their workaround.
2, kodi + libnfs doing the same and failing.

**Comment by sahlberg** [comment]
Can you collect a wirestark trace for each of osz and libnfs+kodi so I can
compare.

It shouldn't be too hard to implement a workaround once I know exactly how
that server+fs combination is "unusual".

**Comment by cjthompson** [comment]
Could you provide me a sample `tcpdump` command to run to capture only NFS traffic?

**Comment by optio50** [comment]
Any progress on this? I believe I have the same issue.

**Comment by rickysarraf** [comment]
I have the same issue but my Linux client can access the NFS share perfectly fine. It is only the Kodi Android build that exhibits this problem

**Comment by rickysarraf** [comment]
> I have the same issue but my Linux client can access the NFS share perfectly fine. It is only the Kodi Android build that exhibits this problem

This could very well be a server-side problem. I re-did the problematic share from `/media/SSHD/Videos` to `/media/SSHD` and now everything is working so far.


With the problematic share name, with nfstrace I got:

```
10.42.0.236:54814 --> 10.42.0.1:2049 [TCP]LOOKUP                                                                                                  
        CALL  [ what:  dir: 0100010005000000 name: XXXXXXX
        REPLY [ status:  ]                                                                                                                        
10.42.0.236:54814 --> 10.42.0.1:2049 [TCP]LOOKUP                                                                                                  
        CALL  [ what:  dir: 0100010005000000 name: YYYYYYY
        REPLY [ status:  ]                                                                                                                        
10.42.0.236:54814 --> 10.42.0.1:2049 [TCP]LOOKUP                                                                                                  
        CALL  [ what:  dir: 0100010005000000 name: ZZZZZZZZ
        REPLY [ status:  ]                                                                                                                        
```

With the renamed share, I now get:

```
10.42.0.236:54814 --> 10.42.0.1:2049 [TCP]LOOKUP
        CALL  [ what:  dir: 0100010004000000 name: XXXXXXXX
        REPLY [ status: OK ]
10.42.0.236:54814 --> 10.42.0.1:2049 [TCP]LOOKUP
        CALL  [ what:  dir: 0100010004000000 name: YYYYYYYY
        REPLY [ status: OK ]
10.42.0.236:54814 --> 10.42.0.1:2049 [TCP]LOOKUP
        CALL  [ what:  dir: 0100010004000000 name: ZZZZZZZZZ
        REPLY [ status: OK ]
```
