### ISSUE TITLE
Crash stemming from nfs_truncate_continue_internal() not fully initializing a struct nfsfh

### ISSUE THREAD

**Issue by ahilananantha** [sahlberg/libnfs#152]
I encountered a crash during a truncate operation.

This issue originated with the "Discard readahead cache on pwrite and truncate too" commit on Feb 24 remains after the code was changed in the commit for "libnfs: add a pagecache" on May 13.

In nfs_truncate_continue_internal() a `struct nfsfh` is created on the stack and only the `fh` field is set:

```
struct nfsfh nfsfh;

nfsfs.fh = data->fh;
```

leaving the rest of the fields uninitialized. A pointer to `nfsfh` is then passed to `nfs_ftruncate_async()`.

In the current code, `nfs_ftruncate_async()` calls `nfs_page_cache_invalidate()` with nfsfh. And then:

```
void nfs_pagecache_invalidate(struct nfs_context *nfs, struct nfsfh *nfsfh) {
	if (nfsfh->pagecache.entries) {
		RPC_LOG(nfs->rpc, 2, "invalidating pagecache");
		memset(nfsfh->pagecache.entries, 0x00, sizeof(struct nfs_pagecache_entry) * nfsfh->pagecache.num_entries);
	}
}
```

Since `nfsfh->pagecache.entries` is an uninitialized pointer it crashes on the `memset()`

In the previous version of the code before the May 13 "libnfs: add a pagecache" checkin it crashed instead in `nfs_ra_invalidate()`:

```
static void nfs_ra_invalidate(struct nfsfh *nfsfh) {
	free(nfsfh->ra.buf);
```

since `nfsfh->ra` is also uninitialized.

**Comment by sahlberg** [comment]
Thanks for a very good report.

I have checked in a fix.
