### ISSUE TITLE
NFS3ERR_ISDIR when linking directories

### ISSUE THREAD

**Issue by keeely** [sahlberg/libnfs#154]
I don't know much about the NFS protocol, but I expected:

nfs_link(ref, "/olddir", "/newdir")

to work, but it complains with the above error.  When I tried to link to a file instead, e.g.:

nfs_link(ref, "/blah.txt", "/blahlink.txt")

It just crashed.

**Comment by sahlberg** [comment]
Generally, you can not use hardlinks for directories under unix.
Use nfs_softlink() instead to create a softlink.

**Comment by keeely** [comment]
I guess you mean nfs_symlink().  Either way you rock: Thanks for replying so fast!

Playing around a bit more, it seems I can use nfs_chdir() to change directory and create relative links, but this won't work (pseudo-code):
chdir("subdir")
symlink("../upper", "mylink")
<<< nfs_symlink_async failed >>>

Instead I need to do:
chdir("subdir")
symlink("../upper", "./mylink")

(add the ./ in front).

But it gets the job done.
