### ISSUE TITLE
Linux: build warnings/error

### ISSUE THREAD

**Issue by MilhouseVH** [sahlberg/libnfs#159]
Just an FYI...

On Linux with the latest [nfs/rpc commits](https://github.com/sahlberg/libnfs/compare/a2b37349fa6d69b0b5d540eb7a5056491bbf2bac...0a4f9cd8a82647dec229f108c34371bda7507fd2) I'm seeing a large number of compiler warnings, which you might be interested in.

There's also a build error which we'll try and work around with `-Wno-error=maybe-uninitialized`(I'm not at home until tomorrow) but presumably would be best dealt with by fixing in the code.

http://sprunge.us/edOR

**Comment by MilhouseVH** [comment]
Note: there might be more warnings as I've only posted the tail end of the log - limitations of posting from a phone...

**Comment by sahlberg** [comment]
Thanks.

Should be fixed now.

**Comment by MilhouseVH** [comment]
Many thanks, looks good now (and builds!) :)
