### ISSUE TITLE
"Operation not supported" with NFS share

### ISSUE THREAD

**Issue by WhatsThePlan** [sahlberg/libnfs#161]
i'm encountering a strange issue with libnfs via gvfs in nautilus. i have a nfs share set up on a server with write permissions (i've tried to give files 777 permissions for testing) and i can read, create and update most files but updating tags of flac music files via easytag and exfalso gives the error `operation not supported`. at first i thought my setup was wrong, but if i mount the nfs share manually with `nfs-utils` on arch linux it works fine `sudo mount server:/mnt/backup/Music -t nfs /mnt/test -o rw,sync`. i can then update tags of music files, but when mounting via nautilus/gvfs/libnfs on arch it gives the same error again. did i perhaps forget to configure something?

server settings are `rw, all_squash, sync, anonuid, anongid`

thanks

**Comment by sahlberg** [comment]
So read/write etc are all working. That means that the core nfs part works.
But easytag/exfalso generate errors?

I suspect it could either be that libnfs only support NFS v3 and not v4.
NFSv4 is a lot richer protocol than v3 so there could be things such as
these apps trying to
use extended attributes or similar which does not exist in nfsv3, or it
could be something in the vfs module.

Can you try mounting it and forcing nfsv3 and see if it still works ?
sudo mount server:/mnt/backup/Music -t nfs /mnt/test -o rw,sync,nfsvers=3



If that fails too, please collect two network trace with wireshark:
1, using easytag/exfalso with libnfs
2, using same with nfs-utils mount

**Comment by WhatsThePlan** [comment]
thanks for your reply, i also tried editing a text file that i created and that seems to work fine too. i've tried your suggestion to mount as nfsv3 and everything is still working even with easytag and exfalso. perhaps these applications try to create a sort of temporary file that is not allowed or supported?

**Comment by sahlberg** [comment]
It could be a buf in libnfs for one of the more rare functions,  but there are not many operations on NFSv3, so.
Please collect a wireshark trace for me when it fails so I can verify if there is anything on the wire that goes wrong. Due dilligence and such.

It could also be that gvfs-nfs is not implementing some unusual function that those two applications use which gvfs-nfs does not implement. I don't know much about that codebase but am willing to give a try to check logfiles if something stands out.
Can you collect an strace for these apps and then we can have a ook if it is a particular syscall that is failing.

Use strace like this : 
strace -ttT -o logfile "command"

Collect this too and I can have a look.

**Comment by WhatsThePlan** [comment]
hi, i've sent you a mail to your github mail address because stace and wireshark traces are a bit sensitive and i don't like them remaining publicly on github forever. please let me know if the mail does not arrive soon, i used a somewhat unknown mail provider that may be blocked by gmail or end up in spam.

**Comment by sahlberg** [comment]
I revceived the traces. I will take a quick look at them tonight.

**Comment by WhatsThePlan** [comment]
that is possible. i took a look at gvfs's source for nfs but could find only two "operation not supported" messages and they were related to moving and copying files. i also tried to enable debug mode for gvfs via https://wiki.gnome.org/Projects/gvfs/doc and got some additional logs, but i dont see any errors. only messages like "org.gtk.vfs.Mount:Enumerate" and "org.gtk.vfs.Mount:QueryInfo" and all with failed=0.

on shutdown of easytag, i did get a lot of spam with messages like "gvfsd-nfs[8530]: send_done_cb: The connection was closed (g-io-error-quark, 18)", but this was only at shutdown and not during failure.

**Comment by sahlberg** [comment]
Ok,  then at this point I think you need gvfs folks involved as there isn't
really anything to go on. :-(

**Comment by WhatsThePlan** [comment]
ok seems someone found this issue and created similar issue here https://bugzilla.gnome.org/show_bug.cgi?id=777152

**Comment by ondrejholy** [comment]
@WhatsThePlan, this is not definitely libnfs issue. Let's continue on the mentioned GNOME bug...

@sahlberg, you can close this bug.
