### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by barsnick** [sahlberg/libnfs#176]
Hi, currently it's hard to see (from a glance at the source or the git tree) what has changed from version to version. (And the git log is hard to read for a high level understanding.) This could be practical for packagers, or users who updated but would like to know what's new.

You do have apt descriptions of the changes on the mailing list (e.g. https://groups.google.com/forum/#!topic/libnfs/g9T9_APXRZ0), and these descriptions also made their way into packaging/RPM/libnfs.spec.in. I suggest that they be listed (formally) in a file called Changelog or CHANGES or NEWS or whatever.

For my own sake, what I (as a pseudo-packager) am doing right now is to extract them myself:
```
sed -n '/%changelog/,$p' packaging/RPM/libnfs.spec.in > Changelog
```

Thanks!

**Comment by sahlberg** [comment]
Good idea.
I will do that going forward.

**Comment by sahlberg** [comment]
Changelog has been added.
