### ISSUE TITLE
List and Copy utils Failed With Error

### ISSUE THREAD

**Issue by DHARANIDHARAN993** [sahlberg/libnfs#181]
**Platform : windows server 2012 R2**

I tried to list the NFS server in particular machine nfs-ls listing is working fine. It will list the NFS share. But when I tried to list some directory inside the NFS share folder, I am getting the below error. 

**Command** 
`nfs-ls.exe -D nfs://192.168.103.186`
**Result:**
nfs://192.168.103.186/NFSshare01
Above acommand working as expected. 

when i am trying to list under the NFS Share, getting error. 
**Command** 
`nfs-ls.exe -D nfs://192.168.103.186/NFSshare01`
**Result:**
`Failed to opendir("") opendir call failed with "NFS: READDIRPLUS of  failed with
 NFS3ERR_ACCES(-13)"`

For Linux NFS shares Folder also getting error 
`mount/mnt call failed with "RPC error: Mount failed
with error MNT3ERR_ACCES(13) Permission denied(13)"`

I Checked the permission in NFS Shared. I gave Full access to that particular NFS share.

**Comment by sahlberg** [comment]
This is not a libnfs issue but a problem with your servers configuration.

Your server is returning NFS3ERR_ACCES  which means that you have not set up the permissions properly on the server.

You need to set these shares up to allow "nobody" (uid 65534) permissions to read the directory.

As windows does not traditionally have a unix uid assigned to the current user, libnfs and the utilities will default to use uid 65524 for all I/O.
You can override this and use a specific uid by appending &uid=1234 to the nfs url,   If that is the uid you want to use.
