### ISSUE TITLE
ABI changed without soname change?

### ISSUE THREAD

**Issue by barsnick** [sahlberg/libnfs#182]
Hi,
I updated my distribution's libnfs package (Fedora's 1.9.8) to recent 1.11.0 locally. I was wondering why the packagers weren't doing this upstream. (I think they're probably just asleep.)

Anyway, I wanted to push them to push the new builds, but beforehand I dared to run abi-compliance-checker against both libraries.

I don't have any packages binaries (except a self-built one) which could prove my point, but abi-compliance-checker shows _incompatible_ differences. This means that even if a binary thinks "oh, there's libnfs.so.8, that is just fine for me", it is bound not to work.

Am I wrong in this judgment? Or is it correct, and you did forget to bump the soname with a release which changed the ABI? (I'm just wondering at this point, not judging.)

Because if I'm correct, the distribution can't update the package (as it would break customers), and would need to deploy the update with a subsequent version of the distibution, with rebuilt dependencies (at the risk of breaking non-distribution binaries). Fedora would need to do this before the F26 release, or wait until a new libnfs with a bumped soname comes around, introduce that in F27, and leave F25 and F26 with version 1.9.8, which would be a pity. (Even with a bumped soname, they wouldn't update released distributions. But there needs to be a path for a newer version to finally get in.)

**Comment by sahlberg** [comment]
On Tue, Apr 25, 2017 at 5:14 AM, barsnick <notifications@github.com> wrote:

> Hi,
> I updated my distribution's libnfs package (Fedora's 1.9.8) to recent
> 1.11.0 locally. I was wondering why the packagers weren't doing this
> upstream. (I think they're probably just asleep.)
>
> Anyway, I wanted to push them to push the new builds, but beforehand I
> dared to run abi-compliance-checker against both libraries.
>
> I don't have any packages binaries (except a self-built one) which could
> prove my point, but abi-compliance-checker shows *incompatible*
> differences. This means that even if a binary thinks "oh, there's
> libnfs.so.8, that is just fine for me", it is bound not to work.
>
> Am I wrong in this judgment? Or is it correct, and you did forget to bump
> the soname with a release which changed the ABI? (I'm just wondering at
> this point, not judging.)
>

Oh dear. You are probably correct. Sorry about that (I am much better at
writing low level client code than managing so versions :-( )
That is probably what happened.

> Because if I'm correct, the distribution can't update the package (as it
> would break customers), and would need to deploy the update with a
> subsequent version of the distibution, with rebuilt dependencies (at the
> risk of breaking non-distribution binaries). Fedora would need to do this
> before the F26 release, or wait until a new libnfs with a bumped soname
> comes around, introduce that in F27, and leave F25 and F26 with version
> 1.9.8, which would be a pity. (Even with a bumped soname, they wouldn't
> update released distributions. But there needs to be a path for a newer
> version to finally get in.)
>

How can we solve this for F26?
There are a few very large changes in the library somewhat recently, i.e.
RPC Server support and NFSv4, so bumping the soname could make sense.

I could thus bumb the so version and create a new release of libnfs this
weekend.
Would that be a solutionthat would work for you?  Or would you prefer
something else ?

**Comment by sahlberg** [comment]
Version 2.0.0 of libnfs is now released and it has a bumped so version.
