### ISSUE TITLE
Proposal to allow permissions to be passed along with nfs_mkdir()

### ISSUE THREAD

**Issue by earlchew** [sahlberg/libnfs#189]
For atomicity and usability, allow directory permissions to be specified at the time of creation.

This proposal is to either change `nfs_mkdir()`, or to introduce a new entry point, that would mimic the signature of `mkdir()`:

> int mkdir(const char *pathname, mode_t mode);

The NFS MKDIR RPC call supports specifying the mode for the newly created directory.

**Comment by sahlberg** [comment]
Sounds good to me.

**Comment by sahlberg** [comment]
Hmm,  create a new function nfs_mkdir2() instead and add the argument to it.

**Comment by sahlberg** [comment]
Merged.
