### ISSUE TITLE
Is it Possible to Read a file with permission only for owner of the file.?

### ISSUE THREAD

**Issue by DHARANIDHARAN993** [sahlberg/libnfs#201]
I am trying to read a file in NFS shared folder. The target file having only read/Write permission for owner of the file. I am trying to read that file using Nfs-ls.exe getting error. 
File Permission 
-rw-------

**Error**

> Failed to open file /win_nfs_tes.vmdk: open call failed with "NFS: ACCESS denied
> . Required access r--. Allowed access ---"

**Changed File Permission**
-rw----r--
After enabled the read permission for "Other User" of that particular file. I can able to read the file. 
My Requirement : 
Using Libnfs, i want to read that file without change anything.

**Comment by sahlberg** [comment]
You can change the uid that libnfs uses by using the uid= argument to the url.
See the README file for the url format.
