### ISSUE TITLE
Assertion failed in dup2 of windows.

### ISSUE THREAD

**Issue by zhangyangchina** [sahlberg/libnfs#235]
Expression: (source_fh >= 0 && (unsigned)source_fh < (unsigned)_nhandle).

On windows , dup2 can not used with sockets。

PS: dup2 is called in rpc_connect_sockaddr_async.

Thanks!

**Comment by hdornemann** [comment]
I've come across this same issue.  If a nfs file handle is opened and left idle for ~10 minutes, the socket gets disconnected.  On reconnect dup2 is being used to re-associate the newly connected socket with the old socket descriptor.  As dup2 doesn't work with sockets on windows this throws an exception.

**Comment by sahlberg** [comment]
I take it that this should be resolved by https://github.com/sahlberg/libnfs/pull/267
