### ISSUE TITLE
Build instructions for Windows

### ISSUE THREAD

**Issue by Mansome-GitHub** [sahlberg/libnfs#238]
Not sure if I missed something but there is no build instructions for Windows. I been trying to figure out how to compile this for a while now. There is no README.win32.txt

**Comment by sahlberg** [comment]
You have visual studio build files in win32/libnfs

**Comment by Mansome-GitHub** [comment]
I installed visual studio and tried to build this and got the following error. C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\stdio.h(1933): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration
  ninja: build stopped: subcommand failed.

**Comment by sahlberg** [comment]
I only build via Visual Studio Online and it does not happen there.
It is possible that different versions of the windows api has different conditional support for different functions, such as snprintf.

I think what needs done is to add an #idfef in the file win32/win32_compat.h
to only define it conditionally.
This is the line :
#define snprintf             sprintf_s

I don't know the correct way to do this test under windows as I don't use it, but you could try to change it to something like : 
#ifndef snprintf
#define snprintf             sprintf_s
#endif

If that does not work, then we need someone that is familiar with how to do these kind of conditional API checks under windows to propose the correct solution.

**Comment by crusader-mike** [comment]
cmake build should be working on Linux and Windows now

**Comment by sahlberg** [comment]
Thanks for the fix for cmake.
