### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by haihongwang** [sahlberg/libnfs#239]
During call to nfs_mount(), it calls nfs_mount_async() internally, then this, in turn, calls rpc_connect_program_async(). If this fails, nfs_set_error(nfs, "Failed to start connection") is called:

```
  if (rpc_connect_program_async(nfs->rpc, server,
              MOUNT_PROGRAM, MOUNT_V3,
              nfs3_mount_1_cb, data) != 0) {
    nfs_set_error(nfs, "Failed to start connection");
    free_nfs_cb_data(data);
    return -1;
  }
```
This overwrites any error returned from rpc_connect_program_async() so the eventual caller of nfs_mount() gets a not very useful error message.

It needs to put error messages from rpc_connect_program_async() in the message returned to caller of nfs_mount().

**Comment by sahlberg** [comment]
Thanks!
I fixed this and two other places as well where we did not get a good error string when rpc_connect_program_async() fails.

Please let me know if there are other places you think we need better error strings as well.

**Comment by haihongwang** [comment]
Yeah, rpc_connect_program_async() calls rpc_connect_async() so essentially
errors returned by rpc_connect_async() are overwritten.

Nothing directly out of my mind, but all places calling nfs_set_error() and
rpc_set_error() need to be examined to include errors returned from
function just called.

**Comment by haihongwang** [comment]
Actually there should be one more place to fix:

```
int
rpc_connect_program_async(struct rpc_context *rpc, const char *server,
                          int program, int version,
                          rpc_cb cb, void *private_data)
{
  struct rpc_cb_data *data;

  data = malloc(sizeof(struct rpc_cb_data));
  if (data == NULL) {
    return -1;
  }
  memset(data, 0, sizeof(struct rpc_cb_data));
  data->server       = strdup(server);
  data->program      = program;
  data->version      = version;

  data->cb           = cb;
  data->private_data = private_data;

  if (rpc_connect_async(rpc, server, 111, rpc_connect_program_1_cb,
                              data) != 0) {
    rpc_set_error(rpc, "Failed to start connection");
    free_rpc_cb_data(data);
    return -1;
  }
  return 0;
}
```
rpc_set_error() can overwrite errors returned from rpc_connect_async()

**Comment by sahlberg** [comment]
Fixed.

Thanks.
