### ISSUE TITLE
Plan for the next release?

### ISSUE THREAD

**Issue by yiming9** [sahlberg/libnfs#255]
First I would like to thank you for this great library! I have been a user for a long time. 

Is there any plan to make a new stable release? I see that the last release was about one year ago. Within this year, a considerable number of bugfixes have been merged. Thanks!

**Comment by sahlberg** [comment]
Thanks.

I can cut a new release towards the end of the coming week.

**Comment by sahlberg** [comment]
A new release was released a few days ago.

**Comment by Daniel-Abrecht** [comment]
Could you please push the git tags?

**Comment by sahlberg** [comment]
done
