### ISSUE TITLE
[NFSv4] Wrong opendir command sequence for subdirectories

### ISSUE THREAD

**Issue by djphoenix** [sahlberg/libnfs#262]
`opendir` encodes wrong lookup path (omits last component).

https://github.com/sahlberg/libnfs/blob/master/lib/nfs_v4.c#L3539
I have found that replacing it to `data = init_cb_data_full_path(nfs, path);` solves a problem.
Maybe more picks like this. Please, review...

_P.S. I am working on full-feature LD_PRELOAD module (that **can** work as nginx/php-fpm backend, e.g. in docker without mounting)... Is it interesting? ;)_

**Comment by sahlberg** [comment]
Awesome report. Thanks.

I have fixed this bug and added tests for opendir()


Your work on a LD_PRELOAD module for docker use sounds awesome.  Once you have it ready we can add a pointer to your project from libnfs/README if you want.
