### ISSUE TITLE
Is there an unique uint32_t or uint64_t per message?

### ISSUE THREAD

**Issue by stefbon** [sahlberg/libnfs#264]
Hi,

I'm implementing libnfs to my "super fuse network fs" fs-workspace:

https://github.com/stefbon/fs-workspace

to access nfs3/nfs4 exports on the network.
For example a directory of ro media files.

Now I'm looking for a way to implement the async io. Available is a hashtable, with data about the original request. The key to this hashdata is an unique id per message. Is there one?
In the

**Comment by sahlberg** [comment]
There is a uint32 that is part of the rpc header:   xid.

You many need to add helper functions to read the xid from the various
structures though.

**Comment by stefbon** [comment]
I see there is the value pdu->xid. This is the value I'm looking for.
But how can I get it? The pdu struct is hidden.
There are some sollutions:
a. add an extra argument like:
nfs_fstat_async(nfs, fh, cb, data, &idx)

b. make the call nfs_fstat_async run the cb not only when receiving data, but also just after sending the request to the server. An extra argument/flag is required for this. This looks like the best sollution:

typedef void (* nfs_cb)(int err, struct nfs_context *nfs, void *data, void *private_data, unsigned char when)

where when is one of the values:

#define NFS_CB_WHEN_SEND                      1
#define NFS_CB_WHEN_RECEIVE                 2

mayebe an extra value:

#define NFS_CB_WHEN_ERROR                    3
#define NFS_CB_WHEN_TIMEOUT                 4

This looks like a very good sollution. Also possible is to use the err/status field for this. When receiving or error or timeout it has a negative value, when 0, receiving, when positive it is the idx. Now this may lead to problems since it's a integer, and cannot represent the uint32 value.
Maybe a sollution is make it value 1, when receiving, and data point to the pdu. The cb detects this, and reads the idx value, stores it in the private_data and add the private data in the hashtable using this value.

What do uou think?

Stef

**Comment by sahlberg** [comment]
Lets not change the signature for the callbacks.


However, it should be much easier for you to do this without any changes at
all.
You basically wan a unique identifier to map between the _async() request
you created and when you get a reply.

You can do this using the private data field for the callbacks.


Create a standardized structure that you use for all _async() callbacks and
have it contain a uint64_t idx;
Have idx increment by one for each _async() request you send.

In the callback you can then map this back to the original reqest by
looking at private_data->idx


That gives you both a unique id that you control for the actual requests
and a way to recover that id from the callback.

**Comment by stefbon** [comment]
Yes that works.
Thank you,

Stef Bon
Voorburg
the Netherlands
