### ISSUE TITLE
nfs_find_local_servers() doesn't work.

### ISSUE THREAD

**Issue by ChristianCiach** [sahlberg/libnfs#270]
I am sorry for the bad title and explanation of the issue, but I don't know how to debug it any better than I did.

I come here because I (and many other people over the last few years) noticed that the [browsing of NFS shares inside Kodi just doesn't work](https://forum.kodi.tv/showthread.php?tid=165454). Mounting and consuming the shares works just fine, just not the listing of local NFS servers.

To debug this I downloaded the sources (current master branch) and compiled the example programs. Kodi uses the function nfs_find_local_servers() and so does the example program "nfsclient-listservers.c". 

As expected, executing this program returns nothing - neither my local nfs server (localhost), nor my other nfs server inside the same local network. Both my machines are using Arch Linux. I even tried to use NFSv3 and NFSv2 instead of NFSv4 and even switched from TCP to UDP, but still no success.

I tried to follow the code flow of the example program, but the deeper I get, the less I understand. These functions are called when I execute the program:

`nfs_find_local_servers -> send_nfsd_probes -> rpc_pmap2_callit_async -> rpc_queue_pdu` 

At the end I can see that `rpc_enqueue(&rpc->waitpdu[hash], pdu);` is called and then `rpc_queue_pdu` returns 0. That's where I get lost. ~~I don't see any mechanism that waits for the queue to empty or something like that.~~ I found the poll() with timeout in nfs_find_local_servers(), but unsurprisingly, increasing the timeout doesn't help.

Adding some prints, it seems like the program tries to do a broadcast request to 192.168.0.255:111 (UDP) to request something about MOUNT_PROGRAM (constant value: 100000) version 2. My NFS-servers both show this:
```

# rpcinfo -p
   program vers proto   port  service
    100000    4   tcp    111  portmapper
    100000    3   tcp    111  portmapper
    100000    2   tcp    111  portmapper
    100000    4   udp    111  portmapper
    100000    3   udp    111  portmapper
    100000    2   udp    111  portmapper
    100024    1   udp  47088  status
    100024    1   tcp  34821  status
    100005    1   udp  20048  mountd
    100005    1   tcp  20048  mountd
    100005    2   udp  20048  mountd
    100005    2   tcp  20048  mountd
    100005    3   udp  20048  mountd
    100005    3   tcp  20048  mountd
    100003    3   tcp   2049  nfs
    100003    4   tcp   2049  nfs
    100227    3   tcp   2049  nfs_acl
    100021    1   udp  42041  nlockmgr
    100021    3   udp  42041  nlockmgr
    100021    4   udp  42041  nlockmgr
    100021    1   tcp  36771  nlockmgr
    100021    3   tcp  36771  nlockmgr
    100021    4   tcp  36771  nlockmgr

```

So, it seems like these services are running.

I put a lot of time into debugging this, but this is as far as I got. If you need any further information, I am happy to provide!

**Comment by sahlberg** [comment]
Server only works for NFSv3 where the server is running both Portmapper and Mount daemon.
Neither of these are available on NFSv4-only servers, thus server discovery will not work for NFSv3-only systems.

To do discovery, libnfs uses broadcast RPC to the portmapper to check for existence of the mount daemon.

It uses the same method that this command uses : 

  rpcinfo -b 100005 2

If the rpcinfo command works, then libnfs server discovery should work.

**Comment by ChristianCiach** [comment]
The default nfs.conf of Arch Linux looks like this (excerpt of nfsd section):

```
#[nfsd]
# debug=0
# threads=8
# host=
# port=0
# grace-time=90
# lease-time=90
# udp=n
# tcp=y
# vers2=n
# vers3=y
# vers4=y
# vers4.0=y
# vers4.1=y
# vers4.2=y
# rdma=n
```

You probably need UDP enabled, so I enabled this but still no luck. 

As said, I will tinker with it further later :)

**Comment by sahlberg** [comment]
Take a

**Comment by sahlberg** [comment]
Take a network trace.   You should see a ethernet and IP broadcast to udp port 111 (which is portmapper)
This packet is a Portmapper protocol packet with the procedure CALLIT and it targets rpc program 100005 (which is nfsv2/3 mount daemon).

The server should send a rely back.


Compare it with what the rpcinfo command I gave.   libnfs does the same thing as that rpcinfo command,

**Comment by ChristianCiach** [comment]
Good news! "rpcinfo -b 100005 2" doensn't work :p

As this is most likely not an issue with libntp I am going to close this issue. As soon as I find out that the problem is, of course I will make another comment to explain it.

**Comment by ChristianCiach** [comment]
Okay, by now I believe this to be a bug in bindrpc. A bug like this [happened before](https://bugzilla.redhat.com/show_bug.cgi?id=869365).

rpcinfo works just fine when I target the server directly (executed on the client machine, 192.168.0.201): 
```
$ rpcinfo -T udp 192.168.0.202 100005 2
program 100005 version 2 ready and waiting
```

When using tcpdump and wireshark I can see that the udp packages reach the server (.202) when doing a broadcast (rpcinfo -b). In fact, when listening on port 111, I can even see the broadcasted packages coming in:
```
$ sudo nc -blu 111
[�t���[�Kkodi��[�t���[�Kkodi��^C
```

The problem seems to be that rpcbind just refuses to answer to broadcast requests (just like a few years ago, see linked issue above).

There is no way for me to debug why rpcbind doesn't send any responses, so this is where I have to quit. What a bummer.

**Comment by ChristianCiach** [comment]
Finally found the issue! If I had decided to tinker with NFS just two months earlier, I probably wouldn't have encountered any issues!

But thanks to [this](https://sourceforge.net/p/libtirpc/mailman/message/36377522/) rpcbind doesn't respond to broadcast requests when using the default build configuration. But adding `--enable-rmtcalls` fixed the issue for me:

```
$ rpcinfo -b 100005 2
192.168.0.202.78.80	192.168.0.202
192.168.0.202.78.80	192.168.0.202
fe80::ee92:4e52:14ff:fc6e.78.80	fe80::ee92:4e52:14ff:fc6e
fe80::ee92:4e52:14ff:fc6e.78.80	fe80::ee92:4e52:14ff:fc6e
192.168.0.202.78.80	192.168.0.202
192.168.0.202.78.80	192.168.0.202
fe80::ee92:4e52:14ff:fc6e.78.80	fe80::ee92:4e52:14ff:fc6e
fe80::ee92:4e52:14ff:fc6e.78.80	fe80::ee92:4e52:14ff:fc6e
```
