### ISSUE TITLE
How to implement nfs_umount?

### ISSUE THREAD

**Issue by CharmingYang0** [sahlberg/libnfs#273]
Using this library, each action can be run well.
But once you check the NFS server, you'll find the nfs mount still there.
It's preferred to release the nfs mount after each NFS cycle, but the method is not implemented yet.
I tried to do that upon 

> rpc_mount3_umnt_async

 method with all necessary data collected, but unfortunately        **-14 (BAD ADDRESS)** returned.

I'll appreciate very much that you guide how to achive this feature.

```
static void
nfs3_unmount_cb(struct rpc_context *rpc, int status, void *command_data, void *private_data)
{
	struct nfs_cb_data *data = private_data;
	struct nfs_context *nfs = data->nfs;

	assert(rpc->magic == RPC_CONTEXT_MAGIC);

	if (check_nfs3_error(nfs, status, data, command_data)) {
		free_nfs_cb_data(data);
		return;
	}

	data->cb(0, nfs, NULL, data->private_data);
	free_nfs_cb_data(data);
}

int
nfs3_unmount_async(struct nfs_context *nfs, nfs_cb cb, void *private_data)
{
	struct nfs_cb_data *data;

    data = malloc(sizeof(struct nfs_cb_data));
	if (data == NULL) {
		nfs_set_error(nfs, "out of memory. failed to allocate memory for nfs unmount");
		return -1;
	}
	memset(data, 0, sizeof(struct nfs_cb_data));

	data->nfs          = nfs;
	data->cb           = cb;
	data->private_data = private_data;

    if (rpc_mount3_umnt_async(nfs->rpc, nfs3_unmount_cb, nfs->export, data) != 0){
        nfs_set_error(nfs, "RPC error: Failed to send UMNT call for %s", data->path);
		data->cb(-ENOMEM, nfs, nfs_get_error(nfs), data->private_data);
		free_nfs_cb_data(data);
        return -1;
    }

	return 0;
}
```

**Comment by atmneo** [comment]
I had also tried to add the umount logic.
The code above looks correct. In fact in the callback, if you print the "command_data" --> that may give you additional info for the error code.

In my case, I was seeing the following:
> Server responded: Program not available

After tracing it to the rpc level - I saw that the error is set in the 
`
static int rpc_process_call(struct rpc_context *rpc, ZDR *zdr)
{
	struct rpc_msg call;
        struct rpc_endpoint *endpoint;
        int i, min_version = 0, max_version = 0, found_program = 0;

	assert(rpc->magic == RPC_CONTEXT_MAGIC);

	memset(&call, 0, sizeof(struct rpc_msg));
	if (zdr_callmsg(rpc, zdr, &call) == 0) {
		rpc_set_error(rpc, "Failed to decode CALL message. %s",
                              rpc_get_error(rpc));
                return rpc_send_error_reply(rpc, &call, GARBAGE_ARGS, 0, 0);
        }
        for (endpoint = rpc->endpoints; endpoint; endpoint = endpoint->next) {
                if (call.body.cbody.prog == endpoint->program) {
                        if (!found_program) {
                                min_version = max_version = endpoint->version;
                        }
                        if (endpoint->version < min_version) {
                                min_version = endpoint->version;
                        }
                        if (endpoint->version > max_version) {
                                max_version = endpoint->version;
                        }
                        found_program = 1;
                        if (call.body.cbody.vers == endpoint->version) {
                                break;
                        }
                }
        }
        if (endpoint == NULL) {
		rpc_set_error(rpc, "No endpoint found for CALL "
                              "program:0x%08x version:%d\n",
                              call.body.cbody.prog, call.body.cbody.vers);
                if (!found_program) {
                        return rpc_send_error_reply(rpc, &call, PROG_UNAVAIL,
                                                    0, 0);
                }
                return rpc_send_error_reply(rpc, &call, PROG_MISMATCH,
                                            min_version, max_version);
        }
        for (i = 0; i < endpoint->num_procs; i++) {
                if (endpoint->procs[i].proc == call.body.cbody.proc) {
                        if (endpoint->procs[i].decode_buf_size) {
                                call.body.cbody.args = zdr_malloc(zdr, endpoint->procs[i].decode_buf_size);
                        }
                        if (!endpoint->procs[i].decode_fn(zdr, call.body.cbody.args)) {
                                rpc_set_error(rpc, "Failed to unmarshall "
                                              "call payload");
                                return rpc_send_error_reply(rpc, &call, GARBAGE_ARGS, 0 ,0);
                        }
                        return endpoint->procs[i].func(rpc, &call);
                }
        }

        return rpc_send_error_reply(rpc, &call, PROC_UNAVAIL, 0 ,0);
}
`

What I am unable to understand is - why is the endpoint NULL here? and why do we work with the same program in the mount operation if we are using the same `rpc_allocate_pdu()` call?

On a higher level, it was interesting to note that there is no reference to umount anywhere in libnfs. Was that a conscious choice and what are the implications, apart from showmount entries, for not having a umount call?

**Comment by sahlberg** [comment]
Hi,

The reason for the "program not available" is likely that you try to do the
umount on the nfs context/port.
    if (rpc_mount3_umnt_async(nfs->rpc, nfs3_unmount_cb, nfs->export, data)
!= 0){

nfs->rpc is an rpc context that is bound to port 2049 and is connected to
the NFS server. Only nfs commands can be sent on this context.

The mount(3) protocol is handled by a different server on a different port.
So if you want to use the rpc_mount3_xxx commands then you can't use
nfs->rpc.
You would need to create a new rpc context and then bind it to the mount
protocol, version 3.

I.e.   rpc_connect_program_async(rpc, server, MOUNT_PROGRAM, MOUNT_V3, ...
and then you will be able to use rpc_mount3_xxx

Note, this is all for NFSv3.  NFSv4 does not use a mount server and there
there is no mount/umount command at all.
(thus showmount should not work for NFSv4 client mount)


I never implemented a umount command since it would be a fair amount of
work and it really is not that important.
mount/umount is only for nfsv3  and whether or not you call the mount3_umnt
command or not
does not have any impact on the server at all.
The only thing that it changes is whether the mount will still show up for
the command 'showmount'
which again is IMO a cosmetic issue.
So I just never implemented it and we just tear down the connection.
Note that this is the same as if you would just power-off a client. That
clients nfsv3 mounts will still show up in showmount until you restart the
nfs(or rather the mount) daemon.

**Comment by atmneo** [comment]
Got it. Thanks for the response.

I will try the umount with the new context. And I agree with the showmount issue. It was just semantics that I was looking for -- a mount followed by umount.

**Comment by sahlberg** [comment]
I am not against adding a nfs_umount() command, I just personally
never saw much point.

If you want to add it I am happy to merge a patch into libnfs.

To start you would need a nfs_umount() function that can demultiplex
based on which version of NFS is used.
We need an actual umount for nfs v3, in nfs_v3.c  but the version for
nfsv4 can just be a no-op.

Look at this function for how this demultiplex function might look like :
/*
 * Async call for umounting an nfs share
 */
int
nfs_umount_async(struct nfs_context *nfs, nfs_cb cb, void *private_data)
{
switch (nfs->version) {
        case NFS_V3:
                return nfs3_umount_async(nfs, cb, private_data);
        case NFS_V4:
                /* no-op, just invoke the callback right away */
                (*cb)(0, nfs, NULL, private_data);
                return 0;
        default:
                nfs_set_error(nfs, "%s does not support NFSv%d",
                              __FUNCTION__, nfs->version);
                return -1;
        }
}


nfs3_umount_async() will have to create a new rpc context,   connect
to the mount server, send a umnt command and exit.
The flow of callbacks it needs to follow will probably look similar to
the mount flow in libnfs.c so you can probably copy a bunch of code
from there.

**Comment by CharmingYang0** [comment]
Sorry for my late response.
I'm pleased to get some hints to implement nfs_umount( ).

**Comment by sahlberg** [comment]
Please see current master.
I added a simple nfs_umouont() function that unregister the mount from the mount daemon in v3 and is a no-op in v4.

But, just like a normal nfs clients, if libnfs/application crashes while it has mounted the share but before it has sent the umount command then it might not be possible to unregister it from the mount daemon with less than reboot of the server.
