### ISSUE TITLE
`exportfs` not available on Mac OSX, 

### ISSUE THREAD

**Issue by david-y-lam** [sahlberg/libnfs#276]
```
davidlam-mbp:tests davidlam$ make VERSION=3 test
for TEST in `ls test_*.sh`; do \
		echo "Running $TEST"; \
		echo "--------------"; \
		sh $TEST || exit 1;   \
		echo "--------------"; \
		echo; \
	done
Running test_0100_ls_basic.sh
--------------
basic ls test
Password:
sudo: exportfs: command not found
-n Testing nfs-ls on root of export ...
Failed to mount nfs share : nfs_service failed
[FAILED]
make: *** [test] Error 1
```

A quick Google search seems to show that `exportfs` is not available on Mac OSX.

**Comment by sahlberg** [comment]
I am mac disadvantaged so I can't fix this easily.

I suspect there is some other command line utility on osx that does
the same thing that exportfs does on many of the other unixen.
So what we probably need here is an abstraction for the use of
exportfs in the test scripts and replace it with a shell function that
calls
exportfs by default but calls the osx equivalent when run on osx.
