### ISSUE TITLE
Wrong version number generated by makerpms.sh

### ISSUE THREAD

**Issue by philipp2100** [sahlberg/libnfs#284]
By using `git describe` instead of `git describe --tags`, makerpms.sh will always determine a version 1.9.6<something>, beginning at version 1.9.6, since apparently since then, leightweight tags were used:

https://github.com/sahlberg/libnfs/blob/38b62bcf873c778ebde79707bb0409b6a09ee608/packaging/RPM/makerpms.sh#L53

**Comment by sahlberg** [comment]
Fixed, thanks
