### ISSUE TITLE
[NFS4] How to implement chmod/chown via path (not nfsfh) on existing directory? 

### ISSUE THREAD

**Issue by CharmingYang0** [sahlberg/libnfs#289]
Recently I picked up a history task to implement NFS client that support both v3 and v4.1.
Most features in NFS4 work well except the chmod / chown on existing directory.
If you attempt to chmod via **nfs4_chmod_async_internal( )**, you will be informed **NFS4ERR_ISDIR** as open & close actions are involved.
I made up functions to retrieve file handle (GETFH) of directory and then SETATTR. It responds OK but response of stat command denotes nothing changed.

Below is my codes.

`static void nfs4_chmod_cb(struct rpc_context *rpc, int status, void *command_data, void *private_data)
{
    struct nfs4_cb_data *data = private_data;
    struct nfs_context *nfs = data->nfs;
    COMPOUND4args args;
    COMPOUND4res *res = command_data;
    GETFH4resok *gfhresok;
    struct nfsfh *fh;
    nfs_argop4 op[2];
    int i;
	
    assert(rpc->magic == RPC_CONTEXT_MAGIC);

    if (check_nfs4_error(nfs, status, data, res, "SETATTR")) {
        nfs_set_error(nfs, "check_nfs4_error in nfs4_chmod_cb() failed");
        return;
    }

    if ((i = nfs4_find_op(nfs, data, res, OP_GETFH, "GETFH")) < 0) {
        nfs_set_error(nfs, "cannot find GETFH in response of nfs4_chmod_cb()");
        return;
    }

    gfhresok = &res->resarray.resarray_val[i].nfs_resop4_u.opgetfh.GETFH4res_u.resok4;

    fh = malloc(sizeof(*fh));
    if (fh == NULL) {
        nfs_set_error(nfs, "Out of memory, failed to allocate struct nfsfh");
        data->cb(-ENOMEM, nfs, nfs_get_error(nfs), data->private_data);
        free_nfs4_cb_data(data);
        return;
    }
    memset(fh, 0, sizeof(*fh));
    fh->fh.len = gfhresok->object.nfs_fh4_len;
    fh->fh.val = malloc(fh->fh.len);
    if (fh->fh.val == NULL) {
        nfs_set_error(nfs, "Out of memory, failed to allocate nfsfh");
        data->cb(-ENOMEM, nfs, nfs_get_error(nfs), data->private_data);
        free_nfs4_cb_data(data);
        return;
    }
    memcpy(fh->fh.val, gfhresok->object.nfs_fh4_val, fh->fh.len);

    memset(op, 0, sizeof(op));
    i = nfs4_op_putfh(nfs, &op[0], fh);
    i += nfs4_op_chmod(nfs, &op[i], fh, data->filler.blob3.val);

    memset(&args, 0, sizeof(args));
    args.argarray.argarray_len = i;
    args.argarray.argarray_val = op;

    if (rpc_nfs4_compound_async(nfs->rpc, nfs4_fsync_cb, &args, data) != 0) {
        data->cb(-ENOMEM, nfs, nfs_get_error(nfs), data->private_data);
        free_nfs4_cb_data(data);
        return;
    }
}

int nfs4_chmod_async(struct nfs_context *nfs, const char *path, int mode, nfs_cb cb, void *private_data)
{
    struct nfs4_cb_data *data;
    uint32_t m;

    data = init_cb_data_split_path(nfs, path);
    if (data == NULL) {
        nfs_set_error(nfs, "Initiate callback data failed");
        return -1;
    }

    data->cb =cb;
    data->private_data = private_data;
    data->filler.func = nfs4_populate_getfh;
    data->filler.max_op = 1;

    /* mode value */
    data->filler.blob3.val = malloc(sizeof(uint32_t));
    if (data->filler.blob3.val == NULL) {
        nfs_set_error(nfs, "Out of memory");
        free_nfs4_cb_data(data);
        return -1;
    }
    data->filler.blob3.free = free;
    m = htonl(mode);
    memcpy(data->filler.blob3.val, &m, sizeof(uint32_t));

    if (nfs4_lookup_path_async(nfs, data, nfs4_chmod_cb) < 0) {
        free_nfs4_cb_data(data);
        return -1;
    }
    return 0;
}`

**Comment by lampovo** [comment]
Yeah, this lib has a problem with chmod/chown and directory. 
It try to use OPEN, but it works only with regular file.
I don't see set attr operation. Only:
**data->filler.func = nfs4_populate_getfh;
data->filler.max_op = 1;**

I think it's a problem.
