### ISSUE TITLE
nfs_normalize_path nfs_normalize_path fails on ../../file

### ISSUE THREAD

**Issue by rbalint** [sahlberg/libnfs#292]
Normalization assumes that before `/../` there is a `/`, too, but like in the example that may not be true:

https://github.com/sahlberg/libnfs/blob/9e63589591dc0aae7828a0cac4a7ee1d196e4b6f/lib/libnfs.c#L937

Also this normalization seem to give wrong results with /foo/bar/foo2/../../bar.

**Comment by kkloginid** [comment]
it wont reach here if path does not start with / . 
/* ^[^/] -> error */
	if (path[0] != '/') {
		nfs_set_error(nfs,
			"Absolute path does not start with '/'");
		return -1;
	}

**Comment by kkloginid** [comment]
I think it will take care of in next while ( str = strstr(path,/../) , in one iteration it will jump one back. 
path , tmp and str are all playing in same memory so next while strstr() will jump to second /../ and remove one more previous dir.
