### ISSUE TITLE
Port number in NFS url should be discarded

### ISSUE THREAD

**Issue by cnotin** [sahlberg/libnfs#298]
I use Gnome3 and Nautilus to browse NFS shares.
I have received URLs such as:
> nfs://10.0.0.1:2049/share

Nautilus fails to browse them with an error. Instead if I remove the port number it works fine:
> nfs://10.0.0.1/share

If my understanding is correct, this features uses libnfs.

I have seen in the README that only this syntax is supported:

> nfs://<server|ipv4|ipv6>/path[?arg=val[&arg=val]*]
> 
> Arguments supported by libnfs are :
> [...]
>  nfsport=<port>    : Use this port for NFS instead of using the portmapper.
>  mountport=<port>  : Use this port for the MOUNT protocol instead of
>                      using portmapper. This argument is ignored for NFSv4
>                      as it does not use the MOUNT protocol.

I suggest to ignore the port number next to the hostname in such URLs, instead of failing.

**Comment by sahlberg** [comment]
Good idea. Pushed to master.
