### ISSUE TITLE
connect callback isn't called on rpc_disconnect()

### ISSUE THREAD

**Issue by crusader-mike** [sahlberg/libnfs#303]
Following snippet fails to call `connect_cb()` and leaks related data structure:
```
static void connect_cb(rpc_context* rpc, int status, void* command_data, void *private_data)
{
}

...

    rpc_context* rpc = rpc_init_context();

    int err = rpc_connect_program_async(rpc, "server-address", 
                           MOUNT_PROGRAM, MOUNT_V3, &connect_cb, nullptr);

    rpc_disconnect(rpc, "AAAA");

    rpc_destroy_context(rpc);
```

basically, if program decides to "wrap it up" while connection is being established -- callback isn't called (this may cause issues) and we leak underlying callback structure.

**Comment by sahlberg** [comment]
If rpc_connect_program_async() returns an error then the callback will not be invoked.
That is true for all _async() functions.

Or did I misunderstand your report?

**Comment by sahlberg** [comment]
<clicked wrong button> reopened

**Comment by crusader-mike** [comment]
`rpc_disconnect` goes over all outstanding calls and invokes their callbacks with some error code (like canceled). Unfortunately it doesn't invoke callback passed into `rpc_connect_*` if rpc context state is in "connecting" state. As result related libnfs structure leaks (plus whatever structures user cb was supposed to free will leak too).

**Comment by sahlberg** [comment]
I see,  try this latest patch for master.   It should do what you want I
think.

**Comment by crusader-mike** [comment]
Looks ok. My only concern is `rpc->error_string` being passed into callback (it can be NULL). But (I guess) `NULL` error string passed into callback is ok.
