### ISSUE TITLE
Is there any way to set different auth(pid/uid) infomation for each request of the same nfs_context?

### ISSUE THREAD

**Issue by wsgalaxy** [sahlberg/libnfs#311]
Hi, I want to build a userspace nfs client using libnfs and fuse, since each fuse request may come from different user and contain different uid/gid, I want to use the uid and gid from fuse to send nfs request, but function nfs_set_uid and nfs_set_gid show that I can only set uid/gid for whole nfs_context but not each request, is there any existing way to achieve that? Thanks!!

**Comment by sahlberg** [comment]
That should be possible. Use nfs_set_auth() before each call to the file api.
