### ISSUE TITLE
Is there a plan to support v4.1

### ISSUE THREAD

**Issue by amandeepgautam** [sahlberg/libnfs#314]
Hi,
Is there a plan to support v4.1? If no, how much work would be needed if one plans to do it? What parts of the lib needs to change.

**Comment by sahlberg** [comment]
Not really.
The reason is mostly that the main big feature of v4.1 is pNFS and I doubt it would be meaningful to implement it in libnfs.

Otherwise, excluding pNFS it would not be that hard to add 4.1 support. Just updating the .x file with the new additions, regenerate the corresponding .h/.c files and then start calling/using the new features from the main library.
But I don't think there would be much value in doing it.

**Comment by sahlberg** [comment]
Adding I am not against adding v4.1 support but lacking pNFS support (which I don't think libnfs will have) I personally see little reason to add it.

If you have a compelling reason why 4.1 support would be useful I can reconsider.

**Comment by amandeepgautam** [comment]
Having the support for sessions in NFSv4.1 is a big plus. People are no longer switching to v4 but are switching to v4.1 which require support for sessions. pNFS support is optional.

**Comment by sahlberg** [comment]
Ok,  that is a valid point.
Do you have wireshark captures I can look at for 4.1 multisession?
Are you willing to test if I add session support?

I can't promise anything, but if there is genuine need and use for these features I can make an attempt.

**Comment by amandeepgautam** [comment]
Thanks. Yes, I can help with the testing. I have attached the traces for mount using v4.1. Let me know if these are sufficient. Also, when you think this can be done not as a promise but just to get an idea? 

[mount_tcp_mount_nfs4.pcap.zip](https://github.com/sahlberg/libnfs/files/4619308/mount_tcp_mount_nfs4.pcap.zip)

**Comment by amandeepgautam** [comment]
@sahlberg  Any luck on this?

**Comment by amandeepgautam** [comment]
@sahlberg Just checking if there is any update on this.

**Comment by sahlberg** [comment]
I have added the low level opcodes that are new in 4.1 but not yet added
any code to actually use them.

In a few weeks I may have time to start to add the plumbing to the v4 layer
to actually use these new commands.

**Comment by amandeepgautam** [comment]
@sahlberg awesome, thanks!

**Comment by amandeepgautam** [comment]
@sahlberg gentle ping.

**Comment by amandeepgautam** [comment]
@sahlberg just wondering if there is any progress on this. Apologies for asking again.

**Comment by sahlberg** [comment]
No progress yet.
I hope to find time to do this over the holidays.

**Comment by amandeepgautam** [comment]
@sahlberg thanks! Will be excited to use the feature. I use libsmb2 as well and it's awesome that I would be able to use almost the same code for libnfs. Very elegant.

**Comment by amandeepgautam** [comment]
@sahlberg Sorry to bug you again, but I realized that we are in different countries. Just curious to know when are the holidays?

**Comment by sahlberg** [comment]
On Thu, Oct 29, 2020 at 1:58 PM Aman Deep Gautam <notifications@github.com>
wrote:

> @sahlberg <https://github.com/sahlberg> Sorry to bug you again, but I
> realized that we are in different countries. Just curious to know when are
> the holidays?
>

End of december.  Yule/Christmas and NewYear

**Comment by sahlberg** [comment]
Unfortunately I won't be able to implement this support this holidays as it
may be a lot bigger than I originally thought.

Maybe later during 2021.

**Comment by amandeepgautam** [comment]
@sahlberg Perhaps partial support in a separate branch and I can pick it up the remaining work. later those can be merged in the mainline once completed.

**Comment by amandeepgautam** [comment]
@sahlberg do we have a plan to put the support sometime in future?

**Comment by varunbharill** [comment]
Hi @sahlberg! I am also looking for an NFSv4.1 client library. Is there any plan to support v4.1 in libnfs yet.

**Comment by sahlberg** [comment]
I have no plans for 4.1 because I do not personally need that functionality.
It would not be very hard to add, just a lot of timeconsuming implementation and testing which I do not have cycles for.
I am happy to advice if someone wants to add this support.

It is a somewhat large amount of work. I am open to work under sponsorship.
