### ISSUE TITLE
Memory corruption caused by wrong calculated allocation size in libnfs_zdr_array

### ISSUE THREAD

**Issue by DetlefGolze** [sahlberg/libnfs#315]
The size to allocate (s)  is calculated before the element count (*size) is determined by libnfs_zdr_u_int(). In my test the very first call allocated 0 bytes and then used 4 of them. Visual Studio runtime correctly complains.

Thanks.

Just found that #310 is the same issue.

**Comment by sahlberg** [comment]
Can you send a pull request so you get proper credit in the git history?
