### ISSUE TITLE
kerberos support

### ISSUE THREAD

**Issue by haihongwang** [sahlberg/libnfs#322]
In the NFSv4 rfc:

The Kerberos V5 GSS-API mechanism as described in [RFC4121] MUST be
   implemented with the RPCSEC_GSS services as specified in Table 2.
   Both client and server MUST support each of the pseudo-flavors.

     +--------+-------+----------------------+-----------------------+
     | Number | Name  | Mechanism's OID      | RPCSEC_GSS service    |
     +--------+-------+----------------------+-----------------------+
     | 390003 | krb5  | 1.2.840.113554.1.2.2 | rpc_gss_svc_none      |
     | 390004 | krb5i | 1.2.840.113554.1.2.2 | rpc_gss_svc_integrity |
     | 390005 | krb5p | 1.2.840.113554.1.2.2 | rpc_gss_svc_privacy   |
     +--------+-------+----------------------+-----------------------+

Which one is implemented by libnfs so far?

**Comment by sahlberg** [comment]
None of them.

Libnfs does not have gssapi/kerberos integration at this point.
