### ISSUE TITLE
Porting library to PS3

### ISSUE THREAD

**Issue by bucanero** [sahlberg/libnfs#327]
Hello,

I've cleaned up the code and patches I made to port libnfs to the PS3.
Could you review this commit https://github.com/bucanero/libnfs/commit/c7ad0762d82bdb66f0b7c8935d9bd1e5bac9c9f5 ?

I'd like to hear your comments before I open a PR. 

thanks for your time! 😄

**Comment by bucanero** [comment]
I added some additional changes in https://github.com/bucanero/libnfs/commit/c14a5acb51e0387e5e849afe17b52bba1869f902

I tested the ported library in a simple ps3 homebrew app, and I was able to connect to my NFS share (running on macOS), list directories and files, open files and copy contents to the PS3 without issues 😄 

let me know your feedback, if you think that some patches can be improved or if there's any issue with the code style. If everything looks good I can create a PR.

have a good weekend!

**Comment by sahlberg** [comment]
That looks good to me.
But maybe add a check if PORTLIBS is defined and abort in the make install
target before it starts copying the files.

Please send a PR and I will merge it.

Thanks. This is awesome.

**Comment by sahlberg** [comment]
On Sat, Aug 15, 2020 at 2:31 PM ronnie sahlberg <ronniesahlberg@gmail.com>
wrote:

> That looks good to me.
> But maybe add a check if PORTLIBS is defined and abort in the make install
> target before it starts copying the files.
>
> Please send a PR and I will merge it.
>
> Thanks. This is awesome.
>

BTW. I am really looking forward to not having to use clunky USB sticks or
ftp to copy packages onto my (5, yes I have 5 :-)  ) PS3s.

**Comment by bucanero** [comment]
> That looks good to me. But maybe add a check if PORTLIBS is defined and abort in the make install target before it starts copying the files. Please send a PR and I will merge it. Thanks. This is awesome.

I think that checking for the `PSL1GHT` variable is enough, because the `PORTLIBS` is actually exported by the `ppu_rules` file that gets included in the Makefile, after checking for PSL1GHT
https://github.com/bucanero/libnfs/blob/master/ps3_ppu/Makefile.PS3_PPU
https://github.com/ps3dev/PSL1GHT/blob/master/ppu_rules

I'll double check but I think it's not possible to reach the `make install` without having those defined exports. Next I'll submit a PR so you can merge the changes.

btw, 5 PS3?! 😄  wow, that's a number!... I have _just_ 2, one for homebrew development, and one regular clean PS3 for gaming. Have you done any dev on the ps3?
My next target is the PS4, but I need to get my old fat PS4 out of storage so I can start doing some stuff there too.

**Comment by bucanero** [comment]
PR submitted: #328

**Comment by bucanero** [comment]
hello,

Now that we have ps3 ports for libnfs and libsmb2, I found an issue when you try to use both libraries in the same homebrew app:

```
linking ... SAMPLE.elf
/usr/local/ps3dev/portlibs/ppu/lib/libsmb2.a(compat.o): In function `getaddrinfo':
compat.c:(.opd+0x30): multiple definition of `getaddrinfo'
/usr/local/ps3dev/portlibs/ppu/lib/libnfs.a(ps3_compat.o):ps3_compat.c:(.opd+0x18): first defined here
/usr/local/ps3dev/portlibs/ppu/lib/libsmb2.a(compat.o): In function `.getaddrinfo':
compat.c:(.text.getaddrinfo+0x0): multiple definition of `.getaddrinfo'
/usr/local/ps3dev/portlibs/ppu/lib/libnfs.a(ps3_compat.o):ps3_compat.c:(.text.getaddrinfo+0x0): first defined here
/usr/local/ps3dev/portlibs/ppu/lib/libsmb2.a(compat.o): In function `freeaddrinfo':
compat.c:(.opd+0x48): multiple definition of `freeaddrinfo'
/usr/local/ps3dev/portlibs/ppu/lib/libnfs.a(ps3_compat.o):ps3_compat.c:(.opd+0x30): first defined here
/usr/local/ps3dev/portlibs/ppu/lib/libsmb2.a(compat.o): In function `.freeaddrinfo':
compat.c:(.text.freeaddrinfo+0x0): multiple definition of `.freeaddrinfo'
/usr/local/ps3dev/portlibs/ppu/lib/libnfs.a(ps3_compat.o):ps3_compat.c:(.text.freeaddrinfo+0x0): first defined here
collect2: error: ld returned 1 exit status
```

The issue is that we have defined `getnameinfo()`, `freeaddrinfo()`, and `getaddrinfo ()` in both compatibility wrappers, and those definitions end up colliding.

I know that probably the best option would be the have those functions already on the PSL1GHT SDK, but meanwhile how do you suggest we can fix this issue in the libraries? Rename the functions and add some defines?

**Comment by sahlberg** [comment]
On Mon, Aug 17, 2020 at 11:51 AM Damián Parrino <notifications@github.com>
wrote:

> hello,
>
> Now that we have ps3 ports for libnfs and libsmb2, I found an issue when
> you try to use both libraries in the same homebrew app:
>
> linking ... SAMPLE.elf
> /usr/local/ps3dev/portlibs/ppu/lib/libsmb2.a(compat.o): In function `getaddrinfo':
> compat.c:(.opd+0x30): multiple definition of `getaddrinfo'
> /usr/local/ps3dev/portlibs/ppu/lib/libnfs.a(ps3_compat.o):ps3_compat.c:(.opd+0x18): first defined here
> /usr/local/ps3dev/portlibs/ppu/lib/libsmb2.a(compat.o): In function `.getaddrinfo':
> compat.c:(.text.getaddrinfo+0x0): multiple definition of `.getaddrinfo'
> /usr/local/ps3dev/portlibs/ppu/lib/libnfs.a(ps3_compat.o):ps3_compat.c:(.text.getaddrinfo+0x0): first defined here
> /usr/local/ps3dev/portlibs/ppu/lib/libsmb2.a(compat.o): In function `freeaddrinfo':
> compat.c:(.opd+0x48): multiple definition of `freeaddrinfo'
> /usr/local/ps3dev/portlibs/ppu/lib/libnfs.a(ps3_compat.o):ps3_compat.c:(.opd+0x30): first defined here
> /usr/local/ps3dev/portlibs/ppu/lib/libsmb2.a(compat.o): In function `.freeaddrinfo':
> compat.c:(.text.freeaddrinfo+0x0): multiple definition of `.freeaddrinfo'
> /usr/local/ps3dev/portlibs/ppu/lib/libnfs.a(ps3_compat.o):ps3_compat.c:(.text.freeaddrinfo+0x0): first defined here
> collect2: error: ld returned 1 exit status
>
> The issue is that we have defined getnameinfo(), freeaddrinfo(), and getaddrinfo
> () in both compatibility wrappers, and those definitions end up colliding.
>
> I know that probably the best option would be the have those functions
> already on the PSL1GHT SDK, but meanwhile how do you suggest we can fix
> this issue in the libraries? Rename the functions and add some defines?
>
For libsmb2, the best way should be to update the Makefile and add
     -export-symbols libsmb2.syms
to the linker flags, that way they will not be exported from the library.

For libnfs I unfortunately do not have a libnfs.syms :-(
But if you update the libsmb2 makefile, at least these symbols from libnfs
will not collide with libsmb2.

**Comment by sahlberg** [comment]
On Mon, Aug 17, 2020 at 12:06 PM ronnie sahlberg <ronniesahlberg@gmail.com>
wrote:

>
>
> On Mon, Aug 17, 2020 at 11:51 AM Damián Parrino <notifications@github.com>
> wrote:
>
>> hello,
>>
>> Now that we have ps3 ports for libnfs and libsmb2, I found an issue when
>> you try to use both libraries in the same homebrew app:
>>
>> linking ... SAMPLE.elf
>> /usr/local/ps3dev/portlibs/ppu/lib/libsmb2.a(compat.o): In function `getaddrinfo':
>> compat.c:(.opd+0x30): multiple definition of `getaddrinfo'
>> /usr/local/ps3dev/portlibs/ppu/lib/libnfs.a(ps3_compat.o):ps3_compat.c:(.opd+0x18): first defined here
>> /usr/local/ps3dev/portlibs/ppu/lib/libsmb2.a(compat.o): In function `.getaddrinfo':
>> compat.c:(.text.getaddrinfo+0x0): multiple definition of `.getaddrinfo'
>> /usr/local/ps3dev/portlibs/ppu/lib/libnfs.a(ps3_compat.o):ps3_compat.c:(.text.getaddrinfo+0x0): first defined here
>> /usr/local/ps3dev/portlibs/ppu/lib/libsmb2.a(compat.o): In function `freeaddrinfo':
>> compat.c:(.opd+0x48): multiple definition of `freeaddrinfo'
>> /usr/local/ps3dev/portlibs/ppu/lib/libnfs.a(ps3_compat.o):ps3_compat.c:(.opd+0x30): first defined here
>> /usr/local/ps3dev/portlibs/ppu/lib/libsmb2.a(compat.o): In function `.freeaddrinfo':
>> compat.c:(.text.freeaddrinfo+0x0): multiple definition of `.freeaddrinfo'
>> /usr/local/ps3dev/portlibs/ppu/lib/libnfs.a(ps3_compat.o):ps3_compat.c:(.text.freeaddrinfo+0x0): first defined here
>> collect2: error: ld returned 1 exit status
>>
>> The issue is that we have defined getnameinfo(), freeaddrinfo(), and getaddrinfo
>> () in both compatibility wrappers, and those definitions end up
>> colliding.
>>
>> I know that probably the best option would be the have those functions
>> already on the PSL1GHT SDK, but meanwhile how do you suggest we can fix
>> this issue in the libraries? Rename the functions and add some defines?
>>
> For libsmb2, the best way should be to update the Makefile and add
>      -export-symbols libsmb2.syms
> to the linker flags, that way they will not be exported from the library.
>
> For libnfs I unfortunately do not have a libnfs.syms :-(
> But if you update the libsmb2 makefile, at least these symbols from libnfs
> will not collide with libsmb2.
>
> We should probably also rename them to smb2_getaddrinfo and nfs_getaddrinfo
and add the corresponding #defined to compat.h
to make it easier to debug when there are link failures.

Can you send me a PR that does this?

**Comment by bucanero** [comment]
> We should probably also rename them to smb2_getaddrinfo and nfs_getaddrinfo
> and add the corresponding #defined to compat.h to make it easier to debug when there are link failures. Can you send me a PR that does this?

sure, I'll rename those functions, and add the defines for both libraries. When ready I'll submit a PR on each repo for your review 👍
