### ISSUE TITLE
RPC error using libnfs with NFS v4 only server.

### ISSUE THREAD

**Issue by avuton** [sahlberg/libnfs#334]
Hello, while running MPD with libnfs-4.0.0-4 (from Manjaro/Arch) support I got the following error:

```NFS error on (removed):/mnt/linear/Sound?version=4: nfs_mount_async() failed: RPC error. Program is not available on (removed)```

Mounting filesystem on this client works fine; server is NFSv4 only. I was under the impression version v4 didn't use RPC (not  very familiar, sorry).

Is there some knob I need to turn to make this work?

**Comment by avuton** [comment]
Identical results from 9a10e17.

**Comment by sahlberg** [comment]
It is likely because libnfs only has basic nfs v4.0 support and no nfs v4.1 support. There is another bug open for adding 4.1 as a feature but I have no plans or time to work on it myself unless it is sponsored.
