### ISSUE TITLE
how to set up rpc_context autoreconnect when use row interface?

### ISSUE THREAD

**Issue by oyealex** [sahlberg/libnfs#342]
Hi,
As the title, when use rpc_context in libnfs-raw.h,  how to set up the autoreconnect field of rpc_context while the rpc_set_autoreconnect function is private?

**Comment by sahlberg** [comment]
On Tue, Mar 2, 2021 at 11:30 PM oyealex <notifications@github.com> wrote:

> Hi,
> As the title, when use rpc_context in libnfs-raw.h, how to set up the
> autoreconnect field of rpc_context while the rpc_set_autoreconnect function
> is private?
>
If there is application need to use this function we can make it public.
Please send me a pull request to make this a public function.
I.e. Move it to and document it in include/nfsc/libnfs-raw.h
and also make sure the linker makes it visible by adding to
lib/libnfs-win32.def

regards
ronnie sahlberg
