### ISSUE TITLE
examples binaries not installed 

### ISSUE THREAD

**Issue by Vidya-Kodihalli** [sahlberg/libnfs#345]
nfs-cat, nfs-cp and nfs-ls are installed with make install.
There seem to be useful binaries in examples/ as well but they are not installed and don't have documentation. 

please help me to install binaries in examples/ also

**Comment by sahlberg** [comment]
Thanks for using libnfs!

The examples programs are mostly there for providing example code for developers and not fully usable utilities.
So I don't know which one in particular you want to install.

Maybe nfs-io? But again,  I think that tool is mostly useful for someone that wants to write a test-suite to test specific operations.


That all said, the utils/ set of programs is pretty barren. Do you have ideas of specific programs you would like to have here in the utils/ directory and I can start working on writing proper tools for it.

What programs do you need? tell me and unless they are overly complex I will write them and add to the utils/
direcotry for you.

Thanks for using libnfs!

regards
ronnie sahlberg

**Comment by Vidya-Kodihalli** [comment]
Thanks for Reply

Set of programs in utils/ directory are pretty good. Can you add some programs to inject error while creating, opening, reading and writing a file.

Also, I have seen in README file that libnfs supports NFSV4. I have tried to set NFSv4 but got an error.
please can you tell me how to set version 4.
