### ISSUE TITLE
API to set lastAccessTime and file deletion

### ISSUE THREAD

**Issue by bishnu1184** [sahlberg/libnfs#348]
Hi,

I am new to libnfs forum and I am not sure if this question is already answered somewhere. But l tried to search in already reported issues and libnfs code and I didn't find any good reference. 

To my use case I need to restore 'lastAccessTime' for a file, present on NFS share after I read that using nfs_read() API.
I can get all these file time stamps (created, last modified and last accessed) time using nfs_stat64() or from 'nfsdirent' structure, but I could not find any API using which I can update same.

Also in my use case I may also need to delete some file present on NFS share, I could see the API like nfs_rmdir(), but I couldn't find any api for file deletion, so can someone please help me with both of these APIs ?

Thanks
Bishnu

**Comment by sahlberg** [comment]
To delete a file you call nfs_unlink()
To set atime and mtime use nfs_utimes()

The api in libnfs is meant to mimic posix so the functions for these
operations are just like posix but with a nfs_ prefix.

**Comment by bishnu1184** [comment]
@sahlberg thanks for your quick response.
