### ISSUE TITLE
Kerberos authentication in libNfs

### ISSUE THREAD

**Issue by bishnu1184** [sahlberg/libnfs#350]
Does libNfs support Kerberos authentication ?

**Comment by sahlberg** [comment]
No, but it should not be super hard to add.
You can look at libsmb2 to see examples on how to use MIT kerberos and bing GSS-API to the protocol.
Ok, nfs is slightly different but it should not be too different.

I will not have time to implement it myself in the near future unless someone sponsors me.
But, it should not be that hard to do. Look at libsmb2 for inspiration and sned me a patch if you get it working.

**Comment by sahlberg** [comment]
krb5/krb5i/krb5p are all implemented in current master now.  
Note that this version contains incompatible API changes due to other changes required for zero-copy read.
Check readme file and commit messages carefully.
This will eventually be released as a new major version of the library.
