### ISSUE TITLE
Problems during installation (last step - make install)

### ISSUE THREAD

**Issue by kr1-s** [sahlberg/libnfs#353]
I am trying to perform the last step of the installation - make install. 
This error appears:
![image](https://user-images.githubusercontent.com/1247249/128667818-8490735a-72e4-409b-99d6-c5020b668780.png)

What am I doing wrong?

**Comment by sahlberg** [comment]
I says it can not find libtool.
Maybe you have not installed autotools/libtool correctly.

**Comment by kr1-s** [comment]
I installed all the tools in order and the same way. On RHEL did not work, but on Ubuntu it worked the first time.
