### ISSUE TITLE
What is the major difference between latest master branch and libnfs 4.0.0 release

### ISSUE THREAD

**Issue by GuruprasadUjwal** [sahlberg/libnfs#355]
What is the major difference between latest master branch and libnfs-4.0.0 branch. IS there any issue in 4.0.0 which is fixed in master branch.

**Comment by sahlberg** [comment]
On Mon, Aug 9, 2021 at 5:32 PM GuruprasadUjwal ***@***.***>
wrote:

> What is the major difference between latest master branch and libnfs-4.0.0
> branch. IS there any issue in 4.0.0 which is fixed in master branch.
>

Mainly PS3 support and addition of functions to read the NFSv4 ACL from a
server.
