### ISSUE TITLE
Escaping '?' in NFS URLs

### ISSUE THREAD

**Issue by pprkut** [sahlberg/libnfs#356]
Hello!

I'm involved in a discussion on how to best deal with filenames containing `?` on an NFS share in https://github.com/xbmc/xbmc/issues/16383.

I'm afraid I just don't know enough about the underlying stack to say how it *should* work. What I *know* is that URLs containing literal `?` work fine with libnfs, at least in combination with a synology NAS. However, that seems to contradict RFC 2224, which lists `?` as a reserved character and implies that it should be escaped. Yet, URLs with escaped `?` don't work with libnfs here.

Do you perhaps have some more input on the matter?

**Comment by sahlberg** [comment]
Oh, this is actually a good question. 

Right now, in URLs, I am using the unecaped '?' to separate the URL and the url arguments,
For example nfs://10.10.10.11/path/file?version=4

But '?' characters can also occur in part/file.


I think we should leave the unescaped character '? for the separator between url and argument but then escape all the '?' characters that are part of path/file

**Comment by sahlberg** [comment]
I.e. we should add escaped characters to the function(s) in libnfs that parses URLs.

**Comment by sahlberg** [comment]
I added parsing of escaped characters to libnfs master branch.
Note that the '?' character that is used as the separator between the URL and the list of arguments are NOT escaped.

**Comment by pprkut** [comment]
Awesome! Thank you! :)

**Comment by sahlberg** [comment]
Let me know if there are other things that kodi needs.   Closing this issue as I think this resolves the libnfs part of solving the main issue.
