### ISSUE TITLE
NFS v4.1 is not working.

### ISSUE THREAD

**Issue by GuruprasadUjwal** [sahlberg/libnfs#357]
I saw many commits related to nfs 4.1. is this in working condition.
any major issues is there to support 4.1 version.

**Comment by sahlberg** [comment]
NFSv4.1 is not implemented and there are no plans right now to add it.
While most of the XDR parts for v4.1 is probably there, except for the pNFS parts,
there would still be substantial work required to actually implement it and re-write all the nfsv4.0 helpers
to the new syntax.

It would likely require re-writing lib/nfs_v4.c as a new backend   lib/nfs_v41.c and change calls to the new types and wrap everything inside  a sequence.
Not likely to be very hard to do but very time consuming.

I am happy to take patches that add v4.1.
I could implement a limited set of 4.1 (no pNFS) but it would have to be sponsored work.

**Comment by sahlberg** [comment]
If you are willing to sponsor v4.1, contact me on ronniesahlberg@gmail.com and we can look at the scope and effort it would require.

**Comment by GuruprasadUjwal** [comment]
Thanks you for the response. I am happy to provide patches to v4.1 before that let me understand nfsv4 code more depth.
