### ISSUE TITLE
incomplete type 'struct timeval' - libnfs.h

### ISSUE THREAD

**Issue by jhgit** [sahlberg/libnfs#358]
Compiling something that includes libnfs.h can trigger the following error:

    error: field has incomplete type 'struct timeval'

It seems to me that libnfs.h should include sys/time.h by default and include time.h as the exception.  [POSIX](https://pubs.opengroup.org/onlinepubs/009604499/basedefs/sys/time.h.html) specifies that struct timeval is defined in sys/time.h

The above error occurs if you do the following on FreeBSD and on Linux:

    $ cat /tmp/c.c
    #include <nfsc/libnfs.h>
    $ clang -I/usr/local/include -c -o /dev/null /tmp/c.c
    In file included from /tmp/c.c:1:
    /usr/include/nfsc/libnfs.h:937:23: error: field has incomplete type 'struct timeval'
           struct timeval atime;
                          ^
    /usr/include/nfsc/libnfs.h:937:15: note: forward declaration of 'struct timeval'
           struct timeval atime;
                  ^
    /usr/include/nfsc/libnfs.h:938:23: error: field has incomplete type 'struct timeval'
           struct timeval mtime;
                          ^
    /usr/include/nfsc/libnfs.h:937:15: note: forward declaration of 'struct timeval'
           struct timeval atime;
                  ^
    /usr/include/nfsc/libnfs.h:939:23: error: field has incomplete type 'struct timeval'
           struct timeval ctime;
                          ^
    /usr/include/nfsc/libnfs.h:937:15: note: forward declaration of 'struct timeval'
           struct timeval atime;
                  ^
    3 errors generated.

See also FreeBSD [bug 258376](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258376)

What systems want to use time.h?  Can it be made the exception with whatever #ifdef's are needed for those systems?

It would be easy enough to add more ifdef's (`__FreeBSD__` and `__linux__`), but maybe it would be easier to make sys/time.h the default.  Or maybe add a 'configure' test and make the #include conditional on a HAVE_TIMEVAL_SYS_TIME #define or similar.

**Comment by jhgit** [comment]
I can come up with a patch for this.  Would it be preferred by this project to add conditions to the ifdef in libnfs.h (e.g., add defined(__FreeBSD__)) or to detect which time.h file to include (time.h or sys/time.h) at configure time?

**Comment by sahlberg** [comment]
On Tue, Sep 14, 2021 at 3:44 AM John Hein ***@***.***> wrote:

> I can come up with a patch for this. Would it be preferred by this project
> to add conditions to the ifdef in libnfs.h (e.g., add defined(*FreeBSD*))
> or to detect which time.h file to include (time.h or sys/time.h) at
> configure time?
>

Please send a pull request for this.  You can just add a defined(FreeBSD)
to it.

**Comment by VVD** [comment]
```
--- include/nfsc/libnfs.h.orig
+++ include/nfsc/libnfs.h
@@ -29,7 +29,7 @@

 #include <stdint.h>
 #if defined(__ANDROID__) || defined(AROS) || defined(__PPU__) \
- || ( defined(__APPLE__) && defined(__MACH__) )
+ || ( defined(__APPLE__) && defined(__MACH__) ) || defined(__FreeBSD__)
 #include <sys/time.h>
 #else
 #include <time.h>
```

**Comment by VVD** [comment]
@sahlberg, check please my message above.

**Comment by sahlberg** [comment]
Patch added. thanks.

**Comment by VVD** [comment]
You can close this issue. And please create new release 5.0.2.
Thanks!
