### ISSUE TITLE
Any chance to have a more premissive licensing terms?

### ISSUE THREAD

**Issue by rahmanih** [sahlberg/libnfs#359]
Hi,
I'm planning to use the libnfs on MCU based product, but the LGPLv2.1 is not really adequate for me as the libnfs is going to be <b>statically linked</b> on my final binary.

Is it possible to have  BSD license for the libnfs library itself?

thanks in advance.

haithem.

**Comment by sahlberg** [comment]
On Sun, Sep 19, 2021 at 9:05 PM rahmanih ***@***.***> wrote:

> Hi,
> I'm planning to use the libnfs on MCU based product, but the LGPLv2.1 is
> not really adequate for me as the libnfs is going to be *statically
> linked* on my final binary.
>
> Is it possible to have BSD license for the libnfs library itself?
>

Hi,

No. I am not going to change the licence for the upstream version.
I am not a lawyer, but I don't think there is any difference between
statically or dynamically linked
libraries when it comes to LGPLv2.1.   There may be a difference in LGPLv3
but I am not a lawyer
and can not advice on this.

If you are concerned and want legal advice I can suggest contacting SFLC
and ask them to review your use case
and give advice.

Optionally, I could offer a specific fork/licence of the library for your
company/project that is under a different licence
but the main upstream repository will remain LGPL.


regards
ronnie sahlberg

thanks in advance.

**Comment by rahmanih** [comment]
thanks that's clear!
