### ISSUE TITLE
FTBS: libnfs v5.0.0  nfs_v3.c  implicit function declaration and structure has invalid member

### ISSUE THREAD

**Issue by Corin-EU** [sahlberg/libnfs#371]
libnfs v4.0.0 compiles and installs just fine.

When building the latest v5.0.0, the compilation fails with

     /bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/src/build/libnfs-5.0.0/include -I/usr/src/build/libnfs-5.0.0/include/nfsc -I/usr/src/build/libnfs-5.0.0/mount -I/usr/src/build/libnfs-5.0.0/nfs -I/usr/src/build/libnfs-5.0.0/nfs4 -I/usr/src/build/libnfs-5.0.0/nlm -I/usr/src/build/libnfs-5.0.0/nsm -I/usr/src/build/libnfs-5.0.0/portmap -I/usr/src/build/libnfs-5.0.0/rquota -I/usr/src/build/libnfs-5.0.0/win32 "-D_U_=__attribute__((unused))"  -Wall -Wshadow -Wno-write-strings -Wstrict-prototypes -Wpointer-arith -Wcast-align -Wno-strict-aliasing -Werror -g -O2 -MT libnfs_la-nfs_v3.lo -MD -MP -MF .deps/libnfs_la-nfs_v3.Tpo -c -o libnfs_la-nfs_v3.lo `test -f 'nfs_v3.c' || echo './'`nfs_v3.c

     libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/src/build/libnfs-5.0.0/include -I/usr/src/build/libnfs-5.0.0/include/nfsc -I/usr/src/build/libnfs-5.0.0/mount -I/usr/src/build/libnfs-5.0.0/nfs -I/usr/src/build/libnfs-5.0.0/nfs4 -I/usr/src/build/libnfs-5.0.0/nlm -I/usr/src/build/libnfs-5.0.0/nsm -I/usr/src/build/libnfs-5.0.0/portmap -I/usr/src/build/libnfs-5.0.0/rquota -I/usr/src/build/libnfs-5.0.0/win32 "-D_U_=__attribute__((unused))" -Wall -Wshadow -Wno-write-strings -Wstrict-prototypes -Wpointer-arith -Wcast-align -Wno-strict-aliasing -Werror -g -O2 -MT libnfs_la-nfs_v3.lo -MD -MP -MF .deps/libnfs_la-nfs_v3.Tpo -c nfs_v3.c  -fPIC -DPIC -o .libs/libnfs_la-nfs_v3.o

     nfs_v3.c: In function _nfs3_chdir_continue_internal_:
     nfs_v3.c:4986:9: error: implicit declaration of function _nfs_mt_mutex_lock_ [-Werror=implicit-function-declaration]
         nfs_mt_mutex_lock(&nfs->rpc->rpc_mutex);
         ^
     nfs_v3.c:4986:36: error: _struct rpc_context_ has no member named _rpc_mutex_
         nfs_mt_mutex_lock(&nfs->rpc->rpc_mutex);
                                    ^
     nfs_v3.c:4989:9: error: implicit declaration of function _nfs_mt_mutex_unlock_ [-Werror=implicit-function-declaration]
         nfs_mt_mutex_unlock(&nfs->rpc->rpc_mutex);
         ^
     nfs_v3.c:4989:38: error: _struct rpc_context_ has no member named _rpc_mutex_
         nfs_mt_mutex_unlock(&nfs->rpc->rpc_mutex);

There is also a problem with configure

           checking for _FILE_OFFSET_BITS value needed for large files... no
           configure: line 13368: test: =: unary operator expected
           checking whether SO_BINDTODEVICE is available... yes

line 1368 of configure is

            if test $libnfs_cv_HAVE_PTHREAD = yes; then

Adding double quotes around both the variable and the value fixes the error.   What I do not understand is that if I go into configure.ac there are double quotes around the variable and the value on line 86 

               if test x"$libnfs_cv_HAVE_PTHREAD" = x"yes"; then

which is from where I think the line in configure is generated.  However line 79 of configure.ac

               if test x$ENABLE_PTHREAD = xyes; then

 appears to be missing the necessary double quotes for the test, but adding double quotes here does not make any difference to the generated configure which still has the missing quotes error.

**Comment by asavah** [comment]
Build succeeds if configured with `--enable-pthread` explicitly.
Also the error you mention is gone.
```
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for pthread support... yes
```

So the bug seems to be in handling no-pthread configure/build.

**Comment by heitbaum** [comment]
Non pthread build fixed with
- #372

**Comment by asavah** [comment]
BTW isn't https://github.com/sahlberg/libnfs/blob/master/configure.ac#L78 a typo?

**Comment by sahlberg** [comment]
Ah, yes it is a typo. Fixed.

Thanks!

**Comment by Corin-EU** [comment]
Thank you for the very speedy response to this issue.

With already downloaded v5.0.0 tar archive source

      configure --enable-pthread --prefix="/usr/local"
      ...
      link: gcc -shared  -fPIC -DPIC  .libs/libnfs_la-init.o .libs/libnfs_la-libnfs.o .libs/libnfs_la-libnfs-sync.o .libs/libnfs_la-libnfs-zdr.o .libs/libnfs_la-multithreading.o .libs/libnfs_la-nfs_v3.o .libs/libnfs_la-nfs_v4.o .libs/libnfs_la-pdu.o .libs/libnfs_la-socket.o ../win32/.libs/libnfs_la-win32_compat.o  -Wl,--whole-archive ../mount/.libs/libmount.a ../nfs/.libs/libnfs.a ../nfs4/.libs/libnfs4.a ../nlm/.libs/libnlm.a ../nsm/.libs/libnsm.a ../portmap/.libs/libportmap.a ../rquota/.libs/librquota.a -Wl,--no-whole-archive   -g -O2   -Wl,-soname -Wl,libnfs.so.14 -o .libs/libnfs.so.14.0.

Everything now successfully compiled and installed for libnfs v5..0.0
