### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Kitsune2222** [sahlberg/libnfs#392]
Question about license. This library can be used in proprietary, commercial project? I have questions because of the presence of 3 licenses in particular gpl 3.

**Comment by sahlberg** [comment]
On Mon, 15 Aug 2022 at 15:17, Fennecfox ***@***.***> wrote:

> Question about license. This library can be used in proprietary,
> commercial project? I have questions because of the presence of 3 licenses
> in particular gpl 3.
>

Yes. The library is LGPLv2.1 and can be used in proprietary projects.

Example applications that are provided to demonstrate the use of the
library are in GPL but that does not affect the use of the library itself.
It just means you can look at the example applications to get inspiration,
but not use or cut-n-paste the code from the examples directly.

**Comment by Kitsune2222** [comment]
Ok, thanks!

**Comment by sahlberg** [comment]
thanks for using libnfs.  If you need features or support, I am always open for sponsored work. As long as it can be contributed t the main codebase as lgpl v2.1.
