### ISSUE TITLE
Can libnfs generate NFSv4.1 traffic?

### ISSUE THREAD

**Issue by RidaShamasneh** [sahlberg/libnfs#419]
libnfs appears to generate NFSv4.0 traffic (as indicated in the screenshot below).
![image](https://github.com/sahlberg/libnfs/assets/8396369/51ec49c2-d59d-40b4-ac49-8f1ca92758ff)

Can we utilize libnfs for generate NFSv4.1 traffic?

**Comment by sahlberg** [comment]
No, there is no support planned for 4.1
