### ISSUE TITLE
readme.md references README.win32.txt, but there is no such file

### ISSUE THREAD

**Issue by iljavs** [sahlberg/libnfs#436]
would be nice if the instructions on how to install this on windows would be available. There is a reference to it, but the file isn't actually there.

**Comment by sahlberg** [comment]
I don't have any window machines so I can not test or verify how to install it.
But you can have a look at .github/workflows/build.yml
it builds libnfs for windows (and many other platforms) on every commit pushed to the repo.

  build-windows:
    name: Windows build

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cmake configure
      run: |
        cmake -G "Visual Studio 17 2022" .
    - name: Build (MSVC)
      run: |
        cmake --build .

**Comment by sahlberg** [comment]
readme is updated to no longer reference the missing file
