### ISSUE TITLE
Is it permissible to initialize the NFS channel through the extended main program's socket channel?

### ISSUE THREAD

**Issue by zshuaia** [sahlberg/libnfs#439]
I already have an application that has established socket communication between the server and client. We extended the socket link by defining different rates and message types through various message headers, thereby introducing the concept of multiple channels. Now, I want to implement a folder redirection feature based on the NFS file system in my application.

Can I use the libnfs library for this purpose?
Does libnfs support initialization based on an existing socket link?
I haven't found any relevant solution in the current example code.

**Comment by sahlberg** [comment]
No, it does not support this. It requires its own dedicated socket.
