### ISSUE TITLE
Re: rpc_set_error: set error to "out of memory" if the malloc failed

### ISSUE THREAD

**Issue by linuxsmiths** [sahlberg/libnfs#465]
@sahlberg, I had sent out a PR that conflicts with the above commit. I will not update it now but you can make the following changes which are currently lacking:
1. rpc_destroy_context() also needs to have the awareness of "oom" pointer being special and that should not be de-allocated.
2. We need to release the lock in case we fail with oom error.
3. nfs_set_error{,_locked} must also behave the same for consistency.

**Comment by sahlberg** [comment]
No worries. I will do that tomorrow morning.

**Comment by sahlberg** [comment]
done

**Comment by linuxsmiths** [comment]
> done

thanks! I'm looking on my mobile device but I don't seem to see the equivalent change in nfs_destroy_context()?

**Comment by sahlberg** [comment]
You are right. thanks.
