### ISSUE TITLE
gcc 14.1.1 compilation issue

### ISSUE THREAD

**Issue by RussianE39** [sahlberg/libnfs#483]
In function 'libnfs_accepted_reply',
    inlined from 'libnfs_rpc_reply_body' at libnfs-zdr.c:571:8:
libnfs-zdr.c:494:47: error: 'len' may be used uninitialized [-Werror=maybe-uninitialized]
  494 |                         message_buffer.length = len;
      |                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~
libnfs-zdr.c: In function 'libnfs_rpc_reply_body':
libnfs-zdr.c:476:28: note: 'len' was declared here
  476 |         uint32_t maj, min, len, tmp;
      |                            ^~~

**Comment by sahlberg** [comment]
Thanks.
I have pushed a change to current master that should avoid this.
