### ISSUE TITLE
Need help building 5.0.3 Linux static library (i.e. libnfs.a)

### ISSUE THREAD

**Issue by mhicks-catalogicsoftware** [sahlberg/libnfs#486]
Greetings, can a kind soul help me build the static library version of libfs 5.0.3? I've had no issues building the shared library. Thanks in advance!

**Comment by sahlberg** [comment]
$ git checkout libnfs-5.0.3
$ ./configure --prefix=/usr
$ make
$ ls -l lib/.libs/libnfs.a 
-rw-r--r-- 1 sahlberg sahlberg 2489252 Aug  8 09:22 lib/.libs/libnfs.a
