### ISSUE TITLE
Max file path name supported by libnfs

### ISSUE THREAD

**Issue by bishnu1184** [sahlberg/libnfs#495]
Hi Ronnie,

I would like to know what is the max file path limit supported by libnfs.
As per RFC https://www.rfc-editor.org/rfc/rfc1094.html Max filename limit is 255 and max path limit is 1024.
But when we tested in our environment it look like it failed with following error  for file path more than ~250 characters

__Failed to create directory structure: long_path/2024-10-15 09-46-25AM GMT/[10.105.140.239/home/nfs_share/baseFolder/SubDirectory1/SubDirectory2/SubDirectory3/SubDirectory4/SubDirectory5/SubDirectory6/SubDirectory7/SubDirectory8/SubDirectory9](http://10.105.140.239/home/nfs_share/baseFolder/SubDirectory1/SubDirectory2/SubDirectory3/SubDirectory4/SubDirectory5/SubDirectory6/SubDirectory7/SubDirectory8/SubDirectory9). Error code :**-34** the error message received is mkdir call failed with "NFS4: (path /long_path/2024-10-15 09-46-25AM_GMT/[10.105.140.239/home/nfs_share/baseFolder/SubDirectory1/SubDirectory2/SubDirectory3/SubDirectory4/SubDirectory5/SubDirectory6/SubDirectory7/SubDirectory8](http://10.105.140.239/home/nfs_share/baseFolder/SubDirectory1/SubDirectory2/SubDirectory3/SubDirectory4/SubDirectory5/SubDirectory6/SubDirectory7/SubDirectory8)) failed with NFS4ERR_RESOURCE(-5)"_

**Comment by sahlberg** [comment]
I will have a look at this tomorrow.  Please keep reminding me if I forget.

**Comment by bishnu1184** [comment]
Have you got the opportunity to check this ?

**Comment by sahlberg** [comment]
Looks like it is working in my tests. Notes, these limitations are for the nfs protocol itself. There may be additional length restrictions imposed by the backing filesystems.
Are you testing against windows? I think windows has a ~250 character limitation in its filesystems and that will limit the path sizes for nfs as well.

I tested with a Linux server with EXT4 as the backing filesystem
and I can create individual components that are 255 bytes in size and also directory paths that are longer than 750 characters.



# Test of file component that is 255 characters in length:

$ ./utils/nfs-stat nfs://10.10.10.11/data/SNAP-1/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde
  File:nfs://10.10.10.11/data/SNAP-1/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde
  Size: 4096            Blocks: 8           IO Block: 4096  directory
Inode:266797057   Links 2
Access: (0755/drwxr-xr-x)  Uid: ( 0/root)  Gid: ( 0/root)
Access: Mon Oct 21 06:47:08 2024
Modify: Mon Oct 21 06:47:08 2024
Change: Mon Oct 21 06:47:08 2024

$ ./examples/nfs-io mkdir nfs://10.10.10.11/data/SNAP-1/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde


# Test creating a 255 character long directory name in a 255 character long directory, total path 511 bytes:
./examples/nfs-io mkdir nfs://10.10.10.11/data/SNAP-1/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde

And we can access the 511 bytes long path:
$ ./utils/nfs-stat nfs://10.10.10.11/data/SNAP-1/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde
  File:nfs://10.10.10.11/data/SNAP-1/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde
  Size: 4096            Blocks: 8           IO Block: 4096  directory
Inode:266797058   Links 2
Access: (0755/drwxr-xr-x)  Uid: ( 1000/sahlberg)  Gid: ( 1000/sahlberg)
Access: Mon Oct 21 06:53:12 2024
Modify: Mon Oct 21 06:53:12 2024
Change: Mon Oct 21 06:53:12 2024

# Test creating a dirctory path that is ~750 bytes long:
$ ./examples/nfs-io mkdir nfs://10.10.10.11/data/SNAP-1/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde

**Comment by sahlberg** [comment]
Works here. Limit is likely in the backing filesystem on the server.
