### ISSUE TITLE
nfs4-cat and nfs-cat failed with NFS version 4

### ISSUE THREAD

**Issue by AmanChauhan2020** [sahlberg/libnfs#496]
While trying to run nfs4-cat and nfs-cat command to fetch file content using NFS version 4, it throws assertion error. It shows correct output for NFS version 3.

Command: sudo ./nfs4-cat nfs://<file>
Error:
> OPEN called
> nfs4-cat: init.c:641: rpc_free_iovector: Assertion `v->iov_capacity > RPC_FAST_VECTORS && v->iov_capacity <= RPC_MAX_VECTORS' failed.
> Aborted

Command: sudo nfs-cat nfs://<file>?version=4
Error:
> nfs-cat: init.c:765: rpc_memcpy_cursor: Assertion `v->iov <= v->iov_ref' failed.
> Aborted

Operating System: Ubuntu 20.04
Kerner version: 5.15.0-122-generic

**Comment by sahlberg** [comment]
Those commands just fail with "failed to parse url"  since the url is not a valid nfs url.
