### ISSUE TITLE
RPC-with-TLS support and autotools

### ISSUE THREAD

**Issue by xavierba** [sahlberg/libnfs#500]
I've stumbled on an issue with 6.0.0. It seems gnutls detection was only added for cmake and thus I'm unable to get RPC-with-TLS support with autotools.

I've tried to use cmake, but then I'm unable to change the libdir to what is needed, but that is a different issue and I don't see the point in bothering to switch to cmake just for that one feature anyway.

**Comment by sahlberg** [comment]
Can you try current master?
I added support and it compiles and links with autotools now.

Once you confirm it works I will push a new 6.0.1 bugfix release

**Comment by xavierba** [comment]
Looks good to me, I patched that one commit over latest tarball, gnutls is properly probed and the resulting shared lib links against gnutls. I have not tested further though.
I will take care of building the package in Fedora Rawhide as soon as the new release is done.
Thanks for the quick answer.

**Comment by sahlberg** [comment]
I pushed an updated version containing this fix.
