### ISSUE TITLE
Fail to build for 32 bits arches

### ISSUE THREAD

**Issue by marillat** [sahlberg/libnfs#504]
Debian unstable
gcc 14.2.0
Arches i386, armel and armhf

```
In file included from pdu.c:63:
pdu.c: In function 'rpc_queue_pdu':
/build/libnfs-dmo-6.0.1/include/libnfs-private.h:633:49: error: format '%lu' expects argument of type 'long unsigned int', but argument 6 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
  633 |                         snprintf(xxlogbuf, 255, "libnfs:%d rpc %p " format, level, rpc, ## __VA_ARGS__); \
      |                                                 ^~~~~~~~~~~~~~~~~~~
pdu.c:703:25: note: in expansion of macro 'RPC_LOG'
  703 |                         RPC_LOG(rpc, 2, "Sending AUTH_TLS NULL RPC (%lu bytes)",
      |                         ^~~~~~~
cc1: all warnings being treated as errors
```

**Comment by sahlberg** [comment]
I added a quick fix since the value is guaranteed to always be <2^31 due to protocol restrictions
and regardless of the size of size_t.
Can you test if compiling current master works on your platform and if so I will make a new bugfix release asap.

**Comment by marillat** [comment]
Thanks, that fix build for 32 bits.

**Comment by sahlberg** [comment]
Pushed new version 6.0.2 with this fix and a fix for windows build.
Thanks. Hopefully this will be good now.

I will add a 32 bit build/test target to the github ci coming week so I will detect when the 32bit build breaks next time.

Thanks!
