### ISSUE TITLE
6.0.2 fails to build in mingw-w64

### ISSUE THREAD

**Issue by robUx4** [sahlberg/libnfs#506]
`mingw-w64` has winpthreads support. That means the autotools/CMake detect that pthread is available (although you need to link with `-lpthreads`). The libnfs code use Windows API for threading (good) but the code is not exclusive to `HAVE_PTHREAD`, so some threading code is defined twice. Some types are also defined twice: https://github.com/sahlberg/libnfs/blob/2e7971e1b97454e309eca7a74305fa8ee5efc943/include/libnfs-multithreading.h#L51

The `WIN32` and `HAVE_PTHREAD` code should be exclusive.

**Comment by sahlberg** [comment]
I don't have access to any actual windows machines to build or test.
Please send a pull request.

**Comment by sahlberg** [comment]
I tried to fix it and it still builds on the github workflow.
Please try master and check if this works.
