### ISSUE TITLE
libnfs-raw.h includes files that are not installed

### ISSUE THREAD

**Issue by robUx4** [sahlberg/libnfs#507]
`libnfs-raw.h` is installed with the library (used in VLC). But it includes files that are not installed like `win32_compat.h`: https://github.com/sahlberg/libnfs/blob/2e7971e1b97454e309eca7a74305fa8ee5efc943/include/nfsc/libnfs-raw.h#L43

This makes it impossible to build for Windows with the installed package.

**Comment by sahlberg** [comment]
Hmmm.   I don't build for windows myself   but including it from libnfs-raw.h is definitely wrong.

Possibly some symbols need to be copied from the header into an into an idefed WIN32 block in libnfs-raw.h

If you know how to fix this, a pull request would be appreciated.  I will try builds using the github build workflow for now.

**Comment by sahlberg** [comment]
Seems like we don't actually need that include to compile on windows so I removed it and it still builds for windows on github workflows.

Can you test master.  Is this good enough to fix your issue?
Sorry but Im a linux/unix guy and struggle a lot with the wondows build.
