### ISSUE TITLE
Feature: Add path->filehandle cache

### ISSUE THREAD

**Issue by sahlberg** [sahlberg/libnfs#53]
Performance for path operations such as open() is poor since we perform a lookup for every component of the path, every time.

We should add a path to filehandle cache to store the n most recent paths that were lookedup.

A good place to add this would be to do the "check if path is in cache" in nfs_loopuppath_async after the call to nfs_normalize_path.
If we find the path in the cache we perform a GETATTR to check the mtime to validate the path instead of calling out to nfs_lookup_path_async_internal().

The place in nfs_lookup_path_async_internal() where we are finished looking up a path and invoke the callback is probably a goo place to insert new entries into the path cache.

**Comment by dhanumuli** [comment]
Is there any cache that is already implemented in libnfs? If not, any recommendations for 3rd party LRU cache implementations?
